using HC.WorkflowStepTemplates;
using Volo.Abp.Identity;
using HC;
using HC.Workflows;
using HC.WorkflowTemplates;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.WorkflowStepAssignments;

public class WorkflowStepAssignment : WorkflowStepAssignmentBase
{
    //<suite-custom-code-autogenerated>
    protected WorkflowStepAssignment()
    {
    }

    public WorkflowStepAssignment(Guid id, Guid? stepId, Guid? defaultUserId, bool isPrimary, bool isActive, string? assigneeType = null, Guid? roleId = null)
        : base(id, stepId, defaultUserId, isPrimary, isActive, assigneeType, roleId)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}