using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Reports;

public class Report : ReportBase
{
    //<suite-custom-code-autogenerated>
    protected Report()
    {
    }

    public Report(Guid id, string name, string url, int sortOrder, string? image = null) : base(id, name, url, sortOrder, image)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}