using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.Reports;

public class ReportManager : ReportManagerBase
{
    //<suite-custom-code-autogenerated>
    public ReportManager(IReportRepository reportRepository) : base(reportRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}