namespace HC.CalendarEvents;

public enum EventType
{
    MEETING,
    DEADLINE,
    REMINDER,
    WORKFLOW_ASSIGNED,
    WORKFLOW_COMPLETED,
    TASK_ASSIGNED,
    TASK_ASSIGN_REMOVED,
    TASK_ASSIGN_UPDATED,
    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_UPDATED,
    PROJECT_MEMBER_REMOVED,
    TASK_DUE_SOON,
    CHAT_MESSAGE_NEW,
    CALENDAR_INVITED,
    CALENDAR_REMINDER,
}