using HC.Shared;
using Volo.Abp.Identity;
using HC.ProjectTasks;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectTaskAssignments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Notifications;
using HC.NotificationReceivers;
using Volo.Abp.EventBus.Distributed;
using static HC.Notifications.SourceType;
using static HC.Notifications.EventType;
using static HC.Notifications.RelatedType;
using HC.CalendarEvents;
using HC.CalendarEventParticipants;
using HC.WorkflowStepAssignments;

namespace HC.ProjectTaskAssignments;

public partial class ProjectTaskAssignmentsAppService : ProjectTaskAssignmentsAppServiceBase, IProjectTaskAssignmentsAppService
{
    //<suite-custom-code-autogenerated>
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    protected IRepository<HC.ProjectTasks.ProjectTask, Guid> _projectTaskRepository;
    protected IRepository<Volo.Abp.Identity.IdentityUser, Guid> _identityUserRepository;
    protected IProjectTaskAssignmentRepository _projectTaskAssignmentRepository;
    protected ICalendarEventRepository _calendarEventRepository;
    protected ICalendarEventParticipantRepository _calendarEventParticipantRepository;
    protected IWorkflowAssigneeResolver _workflowAssigneeResolver;

    public ProjectTaskAssignmentsAppService(
        IProjectTaskAssignmentRepository projectTaskAssignmentRepository,
        ProjectTaskAssignmentManager projectTaskAssignmentManager,
        IDistributedCache<ProjectTaskAssignmentDownloadTokenCacheItem, string> downloadTokenCache,
        IRepository<HC.ProjectTasks.ProjectTask, Guid> projectTaskRepository,
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository,
        INotificationRepository notificationRepository,
        INotificationReceiverRepository notificationReceiverRepository,
        IDistributedEventBus distributedEventBus,
        ICalendarEventRepository calendarEventRepository,
        ICalendarEventParticipantRepository calendarEventParticipantRepository,
        IWorkflowAssigneeResolver workflowAssigneeResolver)
        : base(projectTaskAssignmentRepository, projectTaskAssignmentManager, downloadTokenCache, projectTaskRepository, identityUserRepository)
    {
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        _projectTaskRepository = projectTaskRepository;
        _identityUserRepository = identityUserRepository;
        _projectTaskAssignmentRepository = projectTaskAssignmentRepository;
        _calendarEventRepository = calendarEventRepository;
        _calendarEventParticipantRepository = calendarEventParticipantRepository;
        _workflowAssigneeResolver = workflowAssigneeResolver;
    }
    //</suite-custom-code-autogenerated>

    public override async Task<PagedResultDto<LookupDto<Guid>>> GetIdentityUserLookupAsync(LookupRequestDto input)
    {
        if (CurrentUser.IsInRole("admin"))
        {
            return await base.GetIdentityUserLookupAsync(input);
        }

        if (!CurrentUser.Id.HasValue)
        {
            return new PagedResultDto<LookupDto<Guid>>
            {
                TotalCount = 0,
                Items = new List<LookupDto<Guid>>()
            };
        }

        var scopeOuIds = await _workflowAssigneeResolver.GetOrganizationUnitScopeIdsForUserAsync(CurrentUser.Id.Value);
        if (scopeOuIds.Count == 0)
        {
            return new PagedResultDto<LookupDto<Guid>>
            {
                TotalCount = 0,
                Items = new List<LookupDto<Guid>>()
            };
        }

        var query = (await _identityUserRepository.GetQueryableAsync())
            .Where(u => u.IsActive)
            .Where(u => u.OrganizationUnits.Any(ou => scopeOuIds.Contains(ou.OrganizationUnitId)))
            .WhereIf(!string.IsNullOrWhiteSpace(input.Filter), x =>
                (x.UserName != null && x.UserName.Contains(input.Filter)) ||
                (x.Name != null && x.Name.Contains(input.Filter)));

        var lookupData = await query.PageBy(input.SkipCount, input.MaxResultCount).ToDynamicListAsync<Volo.Abp.Identity.IdentityUser>();
        var totalCount = await AsyncExecuter.CountAsync(query);
        return new PagedResultDto<LookupDto<Guid>>
        {
            TotalCount = totalCount,
            Items = ObjectMapper.Map<List<Volo.Abp.Identity.IdentityUser>, List<LookupDto<Guid>>>(lookupData)
        };
    }
    
    // Override CreateAsync to add notification logic
    public override async Task<ProjectTaskAssignmentDto> CreateAsync(ProjectTaskAssignmentCreateDto input)
    {
        // Call base method to create assignment
        var result = await base.CreateAsync(input);

        // Get project task and user information
        var projectTask = await _projectTaskRepository.GetAsync(input.ProjectTaskId);
        var assignedUser = await _identityUserRepository.GetAsync(input.UserId);
        string userFullName = CurrentUser.SurName + " " + CurrentUser.Name; 

        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "TaskAssigned";
        var notificationContentKey = $"TaskAssignedMessage|{projectTask.Code}|{projectTask.Title}|{userFullName ?? L["System"]}";

        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.TASK.ToString(),
            HC.CalendarEvents.EventType.TASK_ASSIGNED.ToString(),
            HC.CalendarEvents.RelatedType.TASK.ToString(),
            "NORMAL",
            projectTask.Id.ToString()
        );

        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);

        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.UserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);

        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.UserId }
            }
        );

        await AddCalendarParticipantForTaskAsync(projectTask.Id, input.UserId);

        return result;
    }
    
    // Override DeleteAsync to add notification logic
    public override async Task DeleteAsync(Guid id)
    {
        // Get assignment info before deleting
        var assignmentWithNav = await _projectTaskAssignmentRepository.GetWithNavigationPropertiesAsync(id);
        var projectTask = assignmentWithNav.ProjectTask;
        var user = assignmentWithNav.User;
        string userFullName = CurrentUser.SurName + " " + CurrentUser.Name; 

        await RemoveCalendarParticipantForTaskAsync(projectTask.Id, user.Id);

        // Call base method to delete assignment
        await base.DeleteAsync(id);

        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "TaskAssignRemoved";
        var notificationContentKey = $"TaskAssignRemovedMessage|{projectTask.Code}|{projectTask.Title}|{userFullName ?? L["System"]}";

        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.TASK.ToString(),
            HC.CalendarEvents.EventType.TASK_ASSIGN_REMOVED.ToString(),
            HC.CalendarEvents.RelatedType.TASK.ToString(),
            "NORMAL",
            projectTask.Id.ToString()
        );

        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);

        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            user.Id,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);

        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { user.Id }
            }
        );
    }
    
    // Override UpdateAsync to add notification logic
    public override async Task<ProjectTaskAssignmentDto> UpdateAsync(Guid id, ProjectTaskAssignmentUpdateDto input)
    {
        // Call base method to update assignment
        var result = await base.UpdateAsync(id, input);
        
        // Get project task and user information
        var projectTask = await _projectTaskRepository.GetAsync(input.ProjectTaskId);
        var assignedUser = await _identityUserRepository.GetAsync(input.UserId);
        string userFullName = CurrentUser.SurName + " " + CurrentUser.Name; 
        
        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "TaskAssignUpdated";
        var notificationContentKey = $"TaskAssignUpdatedMessage|{projectTask.Code}|{projectTask.Title}|{userFullName ?? L["System"]}";
        
        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.TASK.ToString(),
            HC.CalendarEvents.EventType.TASK_ASSIGN_UPDATED.ToString(),
            HC.CalendarEvents.RelatedType.TASK.ToString(),
            "NORMAL",
            projectTask.Id.ToString()
        );
        
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);
        
        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.UserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);
        
        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.UserId }
            }
        );
        
        return result;
    }

    public override async Task DeleteByIdsAsync(List<Guid> projecttaskassignmentIds)
    {
        foreach (var assignmentId in projecttaskassignmentIds)
        {
            var assignmentWithNav = await _projectTaskAssignmentRepository.GetWithNavigationPropertiesAsync(assignmentId);
            await RemoveCalendarParticipantForTaskAsync(assignmentWithNav.ProjectTask.Id, assignmentWithNav.User.Id);
        }

        await base.DeleteByIdsAsync(projecttaskassignmentIds);
    }

    public override async Task DeleteAllAsync(GetProjectTaskAssignmentsInput input)
    {
        var assignments = await _projectTaskAssignmentRepository.GetListWithNavigationPropertiesAsync(
            input.FilterText, input.AssignmentRole, input.AssignedAtMin, input.AssignedAtMax, input.Note, input.ProjectTaskId, input.UserId);

        foreach (var assignment in assignments)
        {
            await RemoveCalendarParticipantForTaskAsync(assignment.ProjectTask.Id, assignment.User.Id);
        }

        await base.DeleteAllAsync(input);
    }

    private async Task AddCalendarParticipantForTaskAsync(Guid taskId, Guid userId)
    {
        var calendarEvent = await FindTaskCalendarEventAsync(taskId);
        if (calendarEvent == null)
        {
            return;
        }

        var alreadyParticipant = await _calendarEventParticipantRepository.AnyAsync(
            p => p.CalendarEventId == calendarEvent.Id && p.IdentityUserId == userId);

        if (alreadyParticipant)
        {
            return;
        }

        var participant = new CalendarEventParticipant(
            GuidGenerator.Create(),
            calendarEvent.Id,
            userId,
            ParticipantResponse.INVITED.ToString(),
            false);
        participant.TenantId = CurrentTenant.Id;
        await _calendarEventParticipantRepository.InsertAsync(participant);
    }

    private async Task RemoveCalendarParticipantForTaskAsync(Guid taskId, Guid userId)
    {
        var calendarEvent = await FindTaskCalendarEventAsync(taskId);
        if (calendarEvent == null)
        {
            return;
        }

        var participantQueryable = await _calendarEventParticipantRepository.GetQueryableAsync();
        var participants = await AsyncExecuter.ToListAsync(
            participantQueryable
                .Where(p => p.CalendarEventId == calendarEvent.Id)
                .Where(p => p.IdentityUserId == userId));

        foreach (var participant in participants)
        {
            await _calendarEventParticipantRepository.DeleteAsync(participant.Id);
        }
    }

    private async Task<CalendarEvent?> FindTaskCalendarEventAsync(Guid taskId)
    {
        var queryable = await _calendarEventRepository.GetQueryableAsync();
        var calendarEvents = await AsyncExecuter.ToListAsync(
            queryable
                .Where(e => e.EventType == HC.CalendarEvents.EventType.TASK_ASSIGNED.ToString())
                .Where(e => e.RelatedType == HC.CalendarEvents.RelatedType.TASK.ToString())
                .Where(e => e.RelatedId == taskId.ToString()));

        return calendarEvents.FirstOrDefault();
    }
}