using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.Reports;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.Reports;

public class ReportsAppService : ReportsAppServiceBase, IReportsAppService
{
    //<suite-custom-code-autogenerated>
    public ReportsAppService(IReportRepository reportRepository, ReportManager reportManager, IDistributedCache<ReportDownloadTokenCacheItem, string> downloadTokenCache) : base(reportRepository, reportManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>

    public virtual Task<PagedResultDto<ReportDto>> GetListForNavigationAsync(GetReportsInput input)
    {
        return GetListAsync(input);
    }
}