using HC.Shared;
using HC.SurveyLocations;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveyCriterias;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;

namespace HC.SurveyCriterias;

public class SurveyCriteriasAppService : SurveyCriteriasAppServiceBase, ISurveyCriteriasAppService
{
    //<suite-custom-code-autogenerated>
    protected IRepository<HC.SurveyCriterias.SurveyCriteria, Guid> _surveyCriteriaRepository;

    public SurveyCriteriasAppService(ISurveyCriteriaRepository surveyCriteriaRepository, SurveyCriteriaManager surveyCriteriaManager, IDistributedCache<SurveyCriteriaDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.SurveyLocations.SurveyLocation, Guid> surveyLocationRepository) : base(surveyCriteriaRepository, surveyCriteriaManager, downloadTokenCache, surveyLocationRepository)
    {
        _surveyCriteriaRepository = surveyCriteriaRepository;
    }
    //</suite-custom-code-autogenerated>
    
    /// <summary>
    /// Public API to get survey criterias by location without authentication
    /// </summary>
    [AllowAnonymous]
    public virtual async Task<List<SurveyCriteriaDto>> GetPublicSurveyCriteriasByLocationAsync(Guid surveyLocationId)
    {
        var queryable = await _surveyCriteriaRepository.GetQueryableAsync();
        var criterias = await AsyncExecuter.ToListAsync(
            queryable
                .Where(x => x.SurveyLocationId == surveyLocationId && x.IsActive && !x.IsDeleted)
                .OrderBy(x => x.DisplayOrder)
        );
        
        return ObjectMapper.Map<List<SurveyCriteria>, List<SurveyCriteriaDto>>(criterias);
    }
}