using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.CalendarEvents;
using HC.Projects;
using HC.ProjectTasks;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.CalendarEvents;

public class CalendarEventsAppService : CalendarEventsAppServiceBase, ICalendarEventsAppService
{
    private readonly IRepository<Project, Guid> _projectRepository;
    private readonly IRepository<ProjectTask, Guid> _projectTaskRepository;

    //<suite-custom-code-autogenerated>
    public CalendarEventsAppService(
        ICalendarEventRepository calendarEventRepository,
        CalendarEventManager calendarEventManager,
        IDistributedCache<CalendarEventDownloadTokenCacheItem, string> downloadTokenCache,
        IRepository<Project, Guid> projectRepository,
        IRepository<ProjectTask, Guid> projectTaskRepository) : base(calendarEventRepository, calendarEventManager, downloadTokenCache)
    {
        _projectRepository = projectRepository;
        _projectTaskRepository = projectTaskRepository;
    }
    //</suite-custom-code-autogenerated>

    public override async Task<PagedResultDto<CalendarEventDto>> GetListAsync(GetCalendarEventsInput input)
    {
        var result = await base.GetListAsync(input);
        if (result.Items == null || !result.Items.Any())
        {
            return result;
        }

        // Batch-load RelatedName and RelatedEntityId for PROJECT and TASK types.
        // RelatedId can be either Code (e.g. "T0000035") or Guid (legacy data).
        var projectItems = result.Items
            .Where(x => x.RelatedType == RelatedType.PROJECT.ToString() && !string.IsNullOrWhiteSpace(x.RelatedId))
            .Select(x => x.RelatedId!)
            .Distinct()
            .ToList();

        var taskItems = result.Items
            .Where(x => x.RelatedType == RelatedType.TASK.ToString() && !string.IsNullOrWhiteSpace(x.RelatedId))
            .Select(x => x.RelatedId!)
            .Distinct()
            .ToList();

        var projectLookup = new Dictionary<string, (Guid Id, string DisplayName)>(StringComparer.OrdinalIgnoreCase);
        var taskLookup = new Dictionary<string, (Guid Id, string DisplayName)>(StringComparer.OrdinalIgnoreCase);

        // Split by Guid vs Code: Guid lookup by Id, Code lookup by Code
        var projectIds = projectItems.Where(x => Guid.TryParse(x, out _)).Select(Guid.Parse).Distinct().ToList();
        var projectCodes = projectItems.Where(x => !Guid.TryParse(x, out _)).Distinct().ToList();

        var taskIds = taskItems.Where(x => Guid.TryParse(x, out _)).Select(Guid.Parse).Distinct().ToList();
        var taskCodes = taskItems.Where(x => !Guid.TryParse(x, out _)).Distinct().ToList();

        if (projectIds.Any() || projectCodes.Any())
        {
            var projectQuery = await _projectRepository.GetQueryableAsync();
            var projects = await AsyncExecuter.ToListAsync(
                projectQuery.Where(x => projectIds.Contains(x.Id) || projectCodes.Contains(x.Code)));
            foreach (var p in projects)
            {
                projectLookup[p.Id.ToString()] = (p.Id, $"{p.Code} - {p.Name}");
                projectLookup[p.Code] = (p.Id, $"{p.Code} - {p.Name}");
            }
        }

        if (taskIds.Any() || taskCodes.Any())
        {
            var taskQuery = await _projectTaskRepository.GetQueryableAsync();
            var tasks = await AsyncExecuter.ToListAsync(
                taskQuery.Where(x => taskIds.Contains(x.Id) || taskCodes.Contains(x.Code)));
            foreach (var t in tasks)
            {
                taskLookup[t.Id.ToString()] = (t.Id, $"{t.Code} - {t.Title}");
                taskLookup[t.Code] = (t.Id, $"{t.Code} - {t.Title}");
            }
        }

        foreach (var item in result.Items)
        {
            if (string.IsNullOrWhiteSpace(item.RelatedId)) continue;

            if (item.RelatedType == RelatedType.PROJECT.ToString() && projectLookup.TryGetValue(item.RelatedId, out var proj))
            {
                item.RelatedName = proj.DisplayName;
                item.RelatedEntityId = proj.Id;
            }
            else if (item.RelatedType == RelatedType.TASK.ToString() && taskLookup.TryGetValue(item.RelatedId, out var task))
            {
                item.RelatedName = task.DisplayName;
                item.RelatedEntityId = task.Id;
            }
        }

        return result;
    }

    public override async Task<CalendarEventDto> GetAsync(Guid id)
    {
        var dto = await base.GetAsync(id);
        await EnrichWithRelatedEntityAsync(new[] { dto });
        return dto;
    }

    /// <summary>
    /// Populate RelatedName and RelatedEntityId for items with RelatedType PROJECT or TASK.
    /// Handles both RelatedId as Code (e.g. "T0000035") and Guid (legacy).
    /// </summary>
    private async Task EnrichWithRelatedEntityAsync(IEnumerable<CalendarEventDto> items)
    {
        var list = items?.Where(x => x != null).ToList();
        if (list == null || !list.Any()) return;

        var projectItems = list
            .Where(x => x.RelatedType == RelatedType.PROJECT.ToString() && !string.IsNullOrWhiteSpace(x.RelatedId))
            .Select(x => x.RelatedId!)
            .Distinct()
            .ToList();

        var taskItems = list
            .Where(x => x.RelatedType == RelatedType.TASK.ToString() && !string.IsNullOrWhiteSpace(x.RelatedId))
            .Select(x => x.RelatedId!)
            .Distinct()
            .ToList();

        var projectLookup = new Dictionary<string, (Guid Id, string DisplayName)>(StringComparer.OrdinalIgnoreCase);
        var taskLookup = new Dictionary<string, (Guid Id, string DisplayName)>(StringComparer.OrdinalIgnoreCase);

        var projectIds = projectItems.Where(x => Guid.TryParse(x, out _)).Select(Guid.Parse).Distinct().ToList();
        var projectCodes = projectItems.Where(x => !Guid.TryParse(x, out _)).Distinct().ToList();

        var taskIds = taskItems.Where(x => Guid.TryParse(x, out _)).Select(Guid.Parse).Distinct().ToList();
        var taskCodes = taskItems.Where(x => !Guid.TryParse(x, out _)).Distinct().ToList();

        if (projectIds.Any() || projectCodes.Any())
        {
            var projectQuery = await _projectRepository.GetQueryableAsync();
            var projects = await AsyncExecuter.ToListAsync(
                projectQuery.Where(x => projectIds.Contains(x.Id) || projectCodes.Contains(x.Code)));
            foreach (var p in projects)
            {
                projectLookup[p.Id.ToString()] = (p.Id, $"{p.Code} - {p.Name}");
                projectLookup[p.Code] = (p.Id, $"{p.Code} - {p.Name}");
            }
        }

        if (taskIds.Any() || taskCodes.Any())
        {
            var taskQuery = await _projectTaskRepository.GetQueryableAsync();
            var tasks = await AsyncExecuter.ToListAsync(
                taskQuery.Where(x => taskIds.Contains(x.Id) || taskCodes.Contains(x.Code)));
            foreach (var t in tasks)
            {
                taskLookup[t.Id.ToString()] = (t.Id, $"{t.Code} - {t.Title}");
                taskLookup[t.Code] = (t.Id, $"{t.Code} - {t.Title}");
            }
        }

        foreach (var item in list)
        {
            if (string.IsNullOrWhiteSpace(item.RelatedId)) continue;

            if (item.RelatedType == RelatedType.PROJECT.ToString() && projectLookup.TryGetValue(item.RelatedId, out var proj))
            {
                item.RelatedName = proj.DisplayName;
                item.RelatedEntityId = proj.Id;
            }
            else if (item.RelatedType == RelatedType.TASK.ToString() && taskLookup.TryGetValue(item.RelatedId, out var task))
            {
                item.RelatedName = task.DisplayName;
                item.RelatedEntityId = task.Id;
            }
        }
    }
}