using Volo.Abp.Identity;
using HC.DocumentAssignments;
using HC.Documents;
using HC.DocumentWorkflowInstances;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Domain.Repositories;
using HC.DocumentWorkflowInstanceLogss;

namespace HC.DocumentWorkflowInstanceLogss;

public class DocumentWorkflowInstanceLogssAppService : DocumentWorkflowInstanceLogssAppServiceBase, IDocumentWorkflowInstanceLogssAppService
{
    private readonly IRepository<Document, Guid> _documentRepository;
    private readonly IRepository<DocumentWorkflowInstance, Guid> _documentWorkflowInstanceRepository;

    //<suite-custom-code-autogenerated>
    public DocumentWorkflowInstanceLogssAppService(
        IDocumentWorkflowInstanceLogsRepository documentWorkflowInstanceLogsRepository,
        DocumentWorkflowInstanceLogsManager documentWorkflowInstanceLogsManager,
        IRepository<HC.DocumentAssignments.DocumentAssignment, Guid> documentAssignmentRepository,
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository,
        IRepository<Document, Guid> documentRepository,
        IRepository<DocumentWorkflowInstance, Guid> documentWorkflowInstanceRepository)
        : base(documentWorkflowInstanceLogsRepository, documentWorkflowInstanceLogsManager, documentAssignmentRepository, identityUserRepository)
    {
        _documentRepository = documentRepository;
        _documentWorkflowInstanceRepository = documentWorkflowInstanceRepository;
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...

    /// <summary>
    /// Dashboard workflow pie chart for the current user — aligned with /document-signing (workflow SourceType, step assignments).
    /// Each document is counted at most once: pending step → unsigned; else done step → signed; else reject/cancel rules → third bucket.
    /// </summary>
    public virtual async Task<WorkflowChartStatisticsDto> GetWorkflowChartStatisticsAsync(DateTime? fromDate = null, DateTime? toDate = null)
    {
        if (!CurrentUser.Id.HasValue)
        {
            return new WorkflowChartStatisticsDto();
        }

        var currentUserId = CurrentUser.Id.Value;

        var assignmentQueryable = await _documentAssignmentRepository.GetQueryableAsync();
        var documentQueryable = await _documentRepository.GetQueryableAsync();
        var instanceQueryable = await _documentWorkflowInstanceRepository.GetQueryableAsync();

        var workflowDocumentQuery = documentQueryable.Where(d => d.SourceType == DocumentSourceType.Workflow);

        var myWorkflowDocIdsQuery = assignmentQueryable
            .Where(a => a.ReceiverUserId == currentUserId && a.WorkflowStepTemplateId != null)
            .Join(workflowDocumentQuery, a => a.DocumentId, d => d.Id, (a, d) => d.Id)
            .Distinct();

        var baseDocQuery = workflowDocumentQuery.Where(d => myWorkflowDocIdsQuery.Contains(d.Id));

        if (fromDate.HasValue)
        {
            var startDate = fromDate.Value.Date;
            baseDocQuery = baseDocQuery.Where(d => d.IncommingDate >= startDate);
        }

        if (toDate.HasValue)
        {
            var toDateEnd = toDate.Value.Date.AddDays(1).AddSeconds(-1);
            baseDocQuery = baseDocQuery.Where(d => d.IncommingDate <= toDateEnd);
        }

        var distinctBaseDocIds = await AsyncExecuter.ToListAsync(baseDocQuery.Select(d => d.Id).Distinct());
        if (distinctBaseDocIds.Count == 0)
        {
            return new WorkflowChartStatisticsDto();
        }

        var myAssignments = await AsyncExecuter.ToListAsync(
            assignmentQueryable.Where(a =>
                distinctBaseDocIds.Contains(a.DocumentId) &&
                a.ReceiverUserId == currentUserId &&
                a.WorkflowStepTemplateId != null));

        var assignmentsByDocId = myAssignments
            .GroupBy(a => a.DocumentId)
            .ToDictionary(g => g.Key, g => g.ToList());

        var instances = await AsyncExecuter.ToListAsync(
            instanceQueryable.Where(i => distinctBaseDocIds.Contains(i.DocumentId)));

        var latestInstanceByDocId = instances
            .GroupBy(i => i.DocumentId)
            .ToDictionary(
                g => g.Key,
                g => g.OrderByDescending(x => x.StartedAt).First());

        var unsigned = 0;
        var signed = 0;
        var rejectedOrCancelled = 0;

        foreach (var docId in distinctBaseDocIds)
        {
            if (!assignmentsByDocId.TryGetValue(docId, out var assigns))
            {
                continue;
            }

            var hasPendingCurrent = assigns.Any(a =>
                a.Status == nameof(DocumentAssignmentStatus.PENDING) &&
                a.IsCurrent);

            if (hasPendingCurrent)
            {
                unsigned++;
                continue;
            }

            var hasDone = assigns.Any(a => a.Status == nameof(DocumentAssignmentStatus.DONE));
            if (hasDone)
            {
                signed++;
                continue;
            }

            latestInstanceByDocId.TryGetValue(docId, out var latestInstance);
            var latestStatus = latestInstance?.Status;

            var userRejectedWorkflow = assigns.Any(a =>
                a.Status == nameof(DocumentAssignmentStatus.REJECTED) &&
                latestStatus == nameof(DocumentWorkflowInstanceStatus.REJECTED));

            var revokedAfterOverdueCancel = assigns.Any(a =>
                a.Status == nameof(DocumentAssignmentStatus.REVOKE) &&
                latestStatus == nameof(DocumentWorkflowInstanceStatus.CANCELLED));

            if (userRejectedWorkflow || revokedAfterOverdueCancel)
            {
                rejectedOrCancelled++;
            }
        }

        var total = unsigned + signed + rejectedOrCancelled;

        return new WorkflowChartStatisticsDto
        {
            SignedCount = signed,
            UnsignedCount = unsigned,
            ReturnedOrRejectedCount = rejectedOrCancelled,
            TotalCount = total
        };
    }
}