using HC.Shared;
using Volo.Abp.Identity;
using HC.DocumentAssignments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.DocumentWorkflowInstanceLogss;

namespace HC.DocumentWorkflowInstanceLogss;

public class DocumentWorkflowInstanceLogssAppService : DocumentWorkflowInstanceLogssAppServiceBase, IDocumentWorkflowInstanceLogssAppService
{
    //<suite-custom-code-autogenerated>
    public DocumentWorkflowInstanceLogssAppService(IDocumentWorkflowInstanceLogsRepository documentWorkflowInstanceLogsRepository, DocumentWorkflowInstanceLogsManager documentWorkflowInstanceLogsManager, IRepository<HC.DocumentAssignments.DocumentAssignment, Guid> documentAssignmentRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(documentWorkflowInstanceLogsRepository, documentWorkflowInstanceLogsManager, documentAssignmentRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
    public virtual async Task<WorkflowChartStatisticsDto> GetWorkflowChartStatisticsAsync(DateTime? fromDate = null, DateTime? toDate = null)
    {
        if (!CurrentUser.Id.HasValue)
        {
            return new WorkflowChartStatisticsDto();
        }

        var currentUserId = CurrentUser.Id.Value;
        var query = (await _documentWorkflowInstanceLogsRepository.GetQueryableAsync())
            .Where(x => x.ActorUserId == currentUserId);

        if (fromDate.HasValue)
        {
            var startDate = fromDate.Value.Date;
            query = query.Where(x => x.CreationTime >= startDate);
        }

        if (toDate.HasValue)
        {
            var endDateExclusive = toDate.Value.Date.AddDays(1);
            query = query.Where(x => x.CreationTime < endDateExclusive);
        }

        var signedCount = await AsyncExecuter.CountAsync(query.Where(x =>
            x.Action == nameof(WorkflowInstanceLogAction.APPROVE) ||
            x.Action == nameof(WorkflowInstanceLogAction.SIGN)));

        var returnedOrRejectedCount = await AsyncExecuter.CountAsync(query.Where(x =>
            x.Action == nameof(WorkflowInstanceLogAction.RETURN) ||
            x.Action == nameof(WorkflowInstanceLogAction.REJECT)));

        var sentCount = await AsyncExecuter.CountAsync(query.Where(x => x.Action == nameof(WorkflowInstanceLogAction.SUBMIT_WORKFLOW)));

        return new WorkflowChartStatisticsDto
        {
            SignedCount = signedCount,
            ReturnedOrRejectedCount = returnedOrRejectedCount,
            SentCount = sentCount,
            TotalCount = signedCount + returnedOrRejectedCount + sentCount
        };
    }
}