using HC.Shared;
using Volo.Abp.Identity;
using HC.DocumentAssignments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.DocumentWorkflowInstanceLogss;

namespace HC.DocumentWorkflowInstanceLogss;

public class DocumentWorkflowInstanceLogssAppService : DocumentWorkflowInstanceLogssAppServiceBase, IDocumentWorkflowInstanceLogssAppService
{
    //<suite-custom-code-autogenerated>
    public DocumentWorkflowInstanceLogssAppService(IDocumentWorkflowInstanceLogsRepository documentWorkflowInstanceLogsRepository, DocumentWorkflowInstanceLogsManager documentWorkflowInstanceLogsManager, IRepository<HC.DocumentAssignments.DocumentAssignment, Guid> documentAssignmentRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(documentWorkflowInstanceLogsRepository, documentWorkflowInstanceLogsManager, documentAssignmentRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}