using HC.Documents;
using HC.Workflows;
using HC.WorkflowTemplates;
using HC.WorkflowStepTemplates;
using HC.Documents;
using HC.Workflows;
using HC.WorkflowTemplates;
using HC.WorkflowStepTemplates;
using HC.Documents;
using HC.Workflows;
using HC.WorkflowTemplates;
using HC.WorkflowStepTemplates;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.DocumentWorkflowInstances;

public class DocumentWorkflowInstance : DocumentWorkflowInstanceBase
{
    //<suite-custom-code-autogenerated>
    protected DocumentWorkflowInstance()
    {
    }

    public DocumentWorkflowInstance(Guid id, Guid documentId, Guid workflowId, Guid workflowTemplateId, Guid currentStepId, string status, DateTime startedAt, DateTime finishedAt) : base(id, documentId, workflowId, workflowTemplateId, currentStepId, status, startedAt, finishedAt)
    {
    }
    //</suite-custom-code-autogenerated>

    public void MarkOverdue(DateTime overdueAt)
    {
        Status = nameof(DocumentWorkflowInstanceStatus.OVERDUE);
        OverdueAt = overdueAt;
    }

    public void MarkInProgress()
    {
        Status = nameof(DocumentWorkflowInstanceStatus.IN_PROGRESS);
        OverdueAt = null;
    }

    public void Complete(DateTime finishedAt)
    {
        Status = nameof(DocumentWorkflowInstanceStatus.COMPLETED);
        FinishedAt = finishedAt;
    }

    public void Return(string? note = null)
    {
        Status = nameof(DocumentWorkflowInstanceStatus.RETURNED);
    }

    public void Reject(string? note = null)
    {
        Status = nameof(DocumentWorkflowInstanceStatus.REJECTED);
    }

    public void Cancel()
    {
        Status = nameof(DocumentWorkflowInstanceStatus.CANCELLED);
    }
}