using HC.Shared;
using HC.SurveySessions;
using HC.SurveyCriterias;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveyResults;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Logging;
using System.Text.Json;

namespace HC.SurveyResults;
[AllowAnonymous]
public class SurveyResultsAppService : SurveyResultsAppServiceBase, ISurveyResultsAppService
{
    protected ILogger<SurveyResultsAppService> _logger { get; set; } = null!;
    public SurveyResultsAppService(
        ILogger<SurveyResultsAppService> logger,
        ISurveyResultRepository surveyResultRepository,
        SurveyResultManager surveyResultManager, 
        IRepository<HC.SurveyCriterias.SurveyCriteria, Guid> surveyCriteriaRepository,
        IRepository<HC.SurveySessions.SurveySession, Guid> surveySessionRepository,
        IDistributedCache<SurveyResultDownloadTokenCacheItem, string> downloadTokenCache) : base(surveyResultRepository, surveyResultManager, downloadTokenCache, surveyCriteriaRepository, surveySessionRepository)
    {
        _logger = logger;
    }
    //</suite-custom-code-autogenerated>
    
    /// <summary>
    /// Public API to create survey result without authentication
    /// </summary>
    [AllowAnonymous]
    public virtual async Task<SurveyResultDto> CreatePublicSurveyResultAsync(SurveyResultCreateDto input)
    {
        try 
        {   

            var surveyCriteria = await _surveyCriteriaRepository.GetAsync(x=> x.Id == input.SurveyCriteriaId);
            var tenantId = surveyCriteria?.TenantId;
            using (CurrentTenant.Change(tenantId))
            {
                //check if survey result already exists
                var surveyResult = await _surveyResultRepository.GetAsync(x=> x.SurveyCriteriaId == input.SurveyCriteriaId && x.SurveySessionId == input.SurveySessionId);
                if (surveyResult != null)
                {
                    //update survey result
                    surveyResult = await _surveyResultManager.UpdateAsync(surveyResult.Id, input.SurveyCriteriaId, input.SurveySessionId, input.Rating);
                }
                else
                {
                    //create survey result
                    surveyResult = await _surveyResultManager.CreateAsync(input.SurveyCriteriaId, input.SurveySessionId, input.Rating);
                }
                return ObjectMapper.Map<SurveyResult, SurveyResultDto>(surveyResult);
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Error creating survey result for session {input.SurveySessionId} and criteria {input.SurveyCriteriaId}");
            throw new UserFriendlyException(ex.Message);
        }
    }
}