using HC.Shared;
using HC.SurveySessions;
using HC.SurveyCriterias;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveyResults;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Logging;
using System.Text.Json;

namespace HC.SurveyResults;
[AllowAnonymous]
public class SurveyResultsAppService : SurveyResultsAppServiceBase, ISurveyResultsAppService
{
    protected ILogger<SurveyResultsAppService> _logger { get; set; } = null!;
    protected ISurveyResultRepository _surveyResultRepository { get; set; } = null!;
    protected SurveyResultManager _surveyResultManager { get; set; } = null!;
    protected IRepository<HC.SurveyCriterias.SurveyCriteria, Guid> _surveyCriteriaRepository { get; set; } = null!;
    protected IRepository<HC.SurveySessions.SurveySession, Guid> _surveySessionRepository { get; set; } = null!;
    
    public SurveyResultsAppService(
        ILogger<SurveyResultsAppService> logger,
        ISurveyResultRepository surveyResultRepository,
        SurveyResultManager surveyResultManager, 
        IRepository<HC.SurveyCriterias.SurveyCriteria, Guid> surveyCriteriaRepository,
        IRepository<HC.SurveySessions.SurveySession, Guid> surveySessionRepository,
        IDistributedCache<SurveyResultDownloadTokenCacheItem, string> downloadTokenCache) : base(surveyResultRepository, surveyResultManager, downloadTokenCache, surveyCriteriaRepository, surveySessionRepository)
    {
        _logger = logger;
        _surveyResultRepository = surveyResultRepository;
        _surveyResultManager = surveyResultManager;
        _surveyCriteriaRepository = surveyCriteriaRepository;
        _surveySessionRepository = surveySessionRepository;
    }
    //</suite-custom-code-autogenerated>
    
    /// <summary>
    /// Public API to create survey result without authentication
    /// </summary>
    [AllowAnonymous]
    public virtual async Task<SurveyResultDto> CreatePublicSurveyResultAsync(SurveyResultCreateDto input)
    {
        try 
        {   

            var surveyCriteria = await _surveyCriteriaRepository.GetAsync(x=> x.Id == input.SurveyCriteriaId);
            var tenantId = surveyCriteria?.TenantId;
            using (CurrentTenant.Change(tenantId))
            {
                //check if survey result already exists
                var surveyResult = await _surveyResultRepository.GetAsync(x=> x.SurveyCriteriaId == input.SurveyCriteriaId && x.SurveySessionId == input.SurveySessionId);
                if (surveyResult != null)
                {
                    //update survey result
                    surveyResult = await _surveyResultManager.UpdateAsync(surveyResult.Id, input.SurveyCriteriaId, input.SurveySessionId, input.Rating);
                }
                else
                {
                    //create survey result
                    surveyResult = await _surveyResultManager.CreateAsync(input.SurveyCriteriaId, input.SurveySessionId, input.Rating);
                }
                return ObjectMapper.Map<SurveyResult, SurveyResultDto>(surveyResult);
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Error creating survey result for session {input.SurveySessionId} and criteria {input.SurveyCriteriaId}");
            throw new UserFriendlyException(ex.Message);
        }
    }

    public virtual async Task<SurveyResultStatisticsDto> GetStatisticsByLocationAsync(Guid? surveyLocationId)
    {
        var statistics = new SurveyResultStatisticsDto();

        try
        {
            var queryable = await _surveyResultRepository.GetQueryableAsync();
            var sessionQueryable = await _surveySessionRepository.GetQueryableAsync();
            var criteriaQueryable = await _surveyCriteriaRepository.GetQueryableAsync();

            // Join SurveyResults with SurveySessions
            var query = from result in queryable
                       join session in sessionQueryable on result.SurveySessionId equals session.Id
                       join criteria in criteriaQueryable on result.SurveyCriteriaId equals criteria.Id
                       where !surveyLocationId.HasValue || session.SurveyLocationId == surveyLocationId.Value
                       select new
                       {
                           result.Rating,
                           criteria.Name,
                           criteria.Code
                       };

            var data = await AsyncExecuter.ToListAsync(query);

            // Calculate rating distribution
            statistics.RatingDistribution = data
                .GroupBy(x => x.Rating)
                .ToDictionary(g => g.Key, g => g.Count());

            // Ensure all ratings 0-5 are present
            for (int i = 0; i <= 5; i++)
            {
                if (!statistics.RatingDistribution.ContainsKey(i))
                {
                    statistics.RatingDistribution[i] = 0;
                }
            }

            // Calculate criteria average ratings
            statistics.CriteriaAverageRatings = data
                .GroupBy(x => x.Name)
                .Select(g => new
                {
                    CriteriaName = g.Key,
                    AverageRating = g.Average(x => x.Rating)
                })
                .OrderBy(x => x.CriteriaName)
                .ToDictionary(x => x.CriteriaName, x => Math.Round(x.AverageRating, 1));

            return statistics;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting survey result statistics");
            return statistics;
        }
    }
}