using HC.Shared;
using HC.SurveySessions;
using HC.SurveyCriterias;
using HC.SurveyLocations;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveyResults;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using Volo.Abp.Data;
using Volo.Abp.Domain.Entities;

namespace HC.SurveyResults;

public class SurveyResultsAppService : SurveyResultsAppServiceBase, ISurveyResultsAppService
{
    protected ILogger<SurveyResultsAppService> _logger { get; set; } = null!;
    protected ISurveyResultRepository _surveyResultRepository { get; set; } = null!;
    protected ISurveyStatisticsQueryRepository _surveyStatisticsQueryRepository { get; set; } = null!;
    protected SurveyResultManager _surveyResultManager { get; set; } = null!;
    protected IRepository<HC.SurveyCriterias.SurveyCriteria, Guid> _surveyCriteriaRepository { get; set; } = null!;
    protected IRepository<HC.SurveySessions.SurveySession, Guid> _surveySessionRepository { get; set; } = null!;
    protected IRepository<SurveyLocation, Guid> _surveyLocationRepository { get; set; } = null!;
    protected IDataFilter _dataFilter { get; set; } = null!;
    
    public SurveyResultsAppService(
        ILogger<SurveyResultsAppService> logger,
        ISurveyResultRepository surveyResultRepository,
        SurveyResultManager surveyResultManager, 
        ISurveyStatisticsQueryRepository surveyStatisticsQueryRepository,
        IRepository<HC.SurveyCriterias.SurveyCriteria, Guid> surveyCriteriaRepository,
        IRepository<HC.SurveySessions.SurveySession, Guid> surveySessionRepository,
        IRepository<SurveyLocation, Guid> surveyLocationRepository,
        IDataFilter dataFilter,
        IDistributedCache<SurveyResultDownloadTokenCacheItem, string> downloadTokenCache) : base(surveyResultRepository, surveyResultManager, downloadTokenCache, surveyCriteriaRepository, surveySessionRepository)
    {
        _logger = logger;
        _surveyResultRepository = surveyResultRepository;
        _surveyResultManager = surveyResultManager;
        _surveyStatisticsQueryRepository = surveyStatisticsQueryRepository;
        _surveyCriteriaRepository = surveyCriteriaRepository;
        _surveySessionRepository = surveySessionRepository;
        _surveyLocationRepository = surveyLocationRepository;
        _dataFilter = dataFilter;
    }
    //</suite-custom-code-autogenerated>
    
    /// <summary>
    /// Public API to create survey result without authentication
    /// </summary>
    [AllowAnonymous]
    public virtual async Task<SurveyResultDto> CreatePublicSurveyResultAsync(SurveyResultCreateDto input)
    {
        try 
        {   

            var surveyCriteria = await _surveyCriteriaRepository.GetAsync(x=> x.Id == input.SurveyCriteriaId);
            var tenantId = surveyCriteria?.TenantId;
            using (CurrentTenant.Change(tenantId))
            {
                //check if survey result already exists
                var surveyResult = await _surveyResultRepository.GetAsync(x=> x.SurveyCriteriaId == input.SurveyCriteriaId && x.SurveySessionId == input.SurveySessionId);
                if (surveyResult != null)
                {
                    //update survey result
                    surveyResult = await _surveyResultManager.UpdateAsync(surveyResult.Id, input.SurveyCriteriaId, input.SurveySessionId, input.Rating);
                }
                else
                {
                    //create survey result
                    surveyResult = await _surveyResultManager.CreateAsync(input.SurveyCriteriaId, input.SurveySessionId, input.Rating);
                }
                return ObjectMapper.Map<SurveyResult, SurveyResultDto>(surveyResult);
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, $"Error creating survey result for session {input.SurveySessionId} and criteria {input.SurveyCriteriaId}");
            throw new UserFriendlyException(L["AnErrorOccurredWhileProcessingYourRequest"]);
        }
    }

    [AllowAnonymous]
    public virtual async Task<List<SurveyResultDto>> CreatePublicSurveyResultsAsync(List<SurveyResultCreateDto> input)
    {
        try 
        {   
            var surveyResults = new List<SurveyResultDto>();
            var firstCriteriaId = input.FirstOrDefault(x=> x.SurveyCriteriaId != default)?.SurveyCriteriaId;
            var surveyCriteria = await _surveyCriteriaRepository.FirstOrDefaultAsync(x=> x.Id == firstCriteriaId);
            var tenantId = surveyCriteria != null ? surveyCriteria.TenantId : null;

            _logger.LogInformation($"Input survey results: {JsonSerializer.Serialize(input)}");
            using (CurrentTenant.Change(tenantId))
            {
                _logger.LogInformation($"Changing tenant to: {tenantId}");
                //check if survey result already exists
                foreach (var surveyResultCreateDto in input)
                {
                    var surveyResult = await _surveyResultRepository.FirstOrDefaultAsync(x=> 
                    x.SurveyCriteriaId == surveyResultCreateDto.SurveyCriteriaId 
                    && x.SurveySessionId == surveyResultCreateDto.SurveySessionId);

                    _logger.LogInformation($"Survey result: {JsonSerializer.Serialize(surveyResult)}");
                    if (surveyResult != null)
                    {
                        _logger.LogInformation($"Updating survey result: {JsonSerializer.Serialize(surveyResult)}");
                        surveyResult = await _surveyResultManager.UpdateAsync(surveyResult.Id, surveyResultCreateDto.SurveyCriteriaId, surveyResultCreateDto.SurveySessionId, surveyResultCreateDto.Rating);
                    }
                    else
                    {
                        _logger.LogInformation($"Creating survey result: {JsonSerializer.Serialize(surveyResultCreateDto)}");
                        surveyResult = await _surveyResultManager.CreateAsync(
                            surveyResultCreateDto.SurveyCriteriaId, 
                            surveyResultCreateDto.SurveySessionId, 
                            surveyResultCreateDto.Rating);
                    }
                    _logger.LogInformation($"Survey result added: {JsonSerializer.Serialize(surveyResult)}");
                    surveyResults.Add(ObjectMapper.Map<SurveyResult, SurveyResultDto>(surveyResult));
                    _logger.LogInformation($"Survey results: {JsonSerializer.Serialize(surveyResults)}");
                }
            }
            _logger.LogInformation($"Survey results: {JsonSerializer.Serialize(surveyResults)}");
            return surveyResults;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating public survey results batch");
            throw new UserFriendlyException(L["AnErrorOccurredWhileProcessingYourRequest"]);
        }
    }

    public virtual async Task<PagedResultDto<SurveyResultSessionSummaryDto>> GetSessionSummaryListAsync(GetSurveyResultSessionSummariesInput input)
    {
        using (_dataFilter.Disable<ISoftDelete>())
        {
            var resultQueryable = await _surveyResultRepository.GetQueryableAsync();
            var sessionQueryable = await _surveySessionRepository.GetQueryableAsync();
            var criteriaQueryable = await _surveyCriteriaRepository.GetQueryableAsync();

            var query =
                from result in resultQueryable
                join session in sessionQueryable on result.SurveySessionId equals session.Id
                join criteria in criteriaQueryable on result.SurveyCriteriaId equals criteria.Id
                where !input.SurveyLocationId.HasValue || session.SurveyLocationId == input.SurveyLocationId.Value
                select new SurveyResultSessionSummaryDto
                {
                    SurveyResultId = result.Id,
                    SurveySessionId = session.Id,
                    SurveyCriteriaId = criteria.Id,
                    SurveyCriteriaName = criteria.Name,
                    Rating = result.Rating,
                    // Keep for backward compatibility on clients still reading this field.
                    AverageRating = result.Rating,
                    FullName = session.FullName,
                    PhoneNumber = session.PhoneNumber,
                    PatientCode = session.PatientCode,
                    Note = session.Note,
                    SurveyTime = session.SurveyTime
                };

            var sorting = string.IsNullOrWhiteSpace(input.Sorting) ? "SurveyTime desc" : input.Sorting;
            var totalCount = await AsyncExecuter.LongCountAsync(query);
            var items = await AsyncExecuter.ToListAsync(
                query.OrderBy(sorting)
                    .PageBy(input.SkipCount, input.MaxResultCount)
            );

            return new PagedResultDto<SurveyResultSessionSummaryDto>
            {
                TotalCount = totalCount,
                Items = items
            };
        }
    }

    public virtual async Task<List<SurveyResultSessionDetailDto>> GetSessionDetailListAsync(GetSurveyResultSessionDetailsInput input)
    {
        using (_dataFilter.Disable<ISoftDelete>())
        {
            var resultQueryable = await _surveyResultRepository.GetQueryableAsync();
            var sessionQueryable = await _surveySessionRepository.GetQueryableAsync();
            var criteriaQueryable = await _surveyCriteriaRepository.GetQueryableAsync();

            var query =
                from result in resultQueryable
                join session in sessionQueryable on result.SurveySessionId equals session.Id
                join criteria in criteriaQueryable on result.SurveyCriteriaId equals criteria.Id
                where result.SurveySessionId == input.SurveySessionId
                where !input.SurveyLocationId.HasValue || session.SurveyLocationId == input.SurveyLocationId.Value
                orderby criteria.Name
                select new SurveyResultSessionDetailDto
                {
                    SurveyResultId = result.Id,
                    SurveySessionId = session.Id,
                    SurveyCriteriaId = criteria.Id,
                    SurveyCriteriaName = criteria.Name,
                    Rating = result.Rating,
                    FullName = session.FullName,
                    PhoneNumber = session.PhoneNumber,
                    PatientCode = session.PatientCode,
                    Note = session.Note,
                    SurveyTime = session.SurveyTime
                };

            return await AsyncExecuter.ToListAsync(query);
        }
    }

    [AllowAnonymous]
    public override async Task<IRemoteStreamContent> GetListAsExcelFileAsync(SurveyResultExcelDownloadDto input)
    {
        await HC.ExcelDownloadAnonymousTokenHelper.ValidateAndConsumeOneTimeExportTokenAsync(_downloadTokenCache, input.DownloadToken, x => x.Token);

        using (_dataFilter.Disable<ISoftDelete>())
        {
            var resultQueryable = await _surveyResultRepository.GetQueryableAsync();
            var sessionQueryable = await _surveySessionRepository.GetQueryableAsync();
            var criteriaQueryable = await _surveyCriteriaRepository.GetQueryableAsync();
            var locationQueryable = await _surveyLocationRepository.GetQueryableAsync();

            var query =
                from result in resultQueryable
                join session in sessionQueryable on result.SurveySessionId equals session.Id
                join criteria in criteriaQueryable on result.SurveyCriteriaId equals criteria.Id
                join location in locationQueryable on session.SurveyLocationId equals location.Id
                where !input.SurveyLocationId.HasValue || session.SurveyLocationId == input.SurveyLocationId.Value
                orderby session.SurveyTime descending, criteria.Name
                select new
                {
                    result.Rating,
                    SurveyCriteriaName = criteria.Name,
                    SurveyLocationName = location.Name,
                    session.FullName,
                    session.PhoneNumber,
                    session.PatientCode,
                    session.Note,
                    session.SurveyTime
                };

            var rows = await AsyncExecuter.ToListAsync(query);

            var items = rows.Select(row => new Dictionary<string, object?>
            {
                ["Điểm đánh giá"] = row.Rating,
                ["Tiêu chí đánh giá"] = row.SurveyCriteriaName,
                ["Vị trí khảo sát"] = row.SurveyLocationName,
                ["Khách hàng"] = row.FullName,
                ["Số điện thoại"] = row.PhoneNumber,
                ["Mã bệnh nhân"] = row.PatientCode,
                ["Ghi chú"] = row.Note,
                ["Thời gian khảo sát"] = row.SurveyTime.ToString("dd/MM/yyyy HH:mm"),
            }).ToList();

            var memoryStream = new MemoryStream();
            await memoryStream.SaveAsAsync(items);
            memoryStream.Seek(0, SeekOrigin.Begin);
            return new RemoteStreamContent(memoryStream, "SurveyResults.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        }
    }

    public virtual async Task<SurveyResultStatisticsDto> GetStatisticsByLocationAsync(Guid? surveyLocationId)
    {
        var statistics = new SurveyResultStatisticsDto();

        try
        {
            _logger.LogInformation("GetStatisticsByLocationAsync Getting survey result statistics for location {SurveyLocationId}", surveyLocationId);
            var queryResult = await _surveyStatisticsQueryRepository.GetStatisticsByLocationAsync(surveyLocationId);

            statistics.TotalReviews = queryResult.TotalReviews;
            statistics.RatingDistribution = queryResult.RatingDistribution;
            statistics.CriteriaAverageRatings = queryResult.CriteriaAverageRatings;

            _logger.LogInformation("GetStatisticsByLocationAsync Criteria Average Ratings: {CriteriaAverageRatings}",
                JsonSerializer.Serialize(statistics.CriteriaAverageRatings));
            return statistics;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting survey result statistics");
            return statistics;
        }
    }
}