FROM mcr.microsoft.com/dotnet/sdk:10.0
RUN echo "BUILD AT: $(date)"
# Install required Linux libraries (LibreOffice + fonts + unoconv) before switching user
RUN apt-get update && apt-get install -y \
    libreoffice \
    libreoffice-writer \
    libreoffice-core \
    python3 \
    python3-uno \
    unoconv \
    fonts-dejavu \
    fonts-dejavu-core \
    fonts-dejavu-extra \
    fonts-noto \
    fonts-noto-cjk \
    fontconfig \
    libfreetype6 \
    libfontconfig1 \
 && rm -rf /var/lib/apt/lists/*

USER $APP_UID
EXPOSE 8080
EXPOSE 8081

COPY bin/Release/net10.0/publish/ app/
WORKDIR /app
ENTRYPOINT ["dotnet", "HC.Blazor.dll"]
