using HC.Shared;
using Volo.Abp.Identity;
using HC.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.UserDepartments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.UserDepartments;

public class UserDepartmentsAppService : UserDepartmentsAppServiceBase, IUserDepartmentsAppService
{
    //<suite-custom-code-autogenerated>
    public UserDepartmentsAppService(IUserDepartmentRepository userDepartmentRepository, UserDepartmentManager userDepartmentManager, IDistributedCache<UserDepartmentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.Departments.Department, Guid> departmentRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(userDepartmentRepository, userDepartmentManager, downloadTokenCache, departmentRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>

    public override async Task<UserDepartmentDto> CreateAsync(UserDepartmentCreateDto input)
    {
        await EnsureDepartmentAssignmentNotDuplicateAsync(input.UserId, input.DepartmentId, excludedUserDepartmentId: null);

        var dto = await base.CreateAsync(input);

        if (input.IsPrimary)
        {
            await DemoteOtherPrimaryDepartmentsAsync(input.UserId, dto.Id);
        }

        return dto;
    }

    public override async Task<UserDepartmentDto> UpdateAsync(Guid id, UserDepartmentUpdateDto input)
    {
        await EnsureDepartmentAssignmentNotDuplicateAsync(input.UserId, input.DepartmentId, excludedUserDepartmentId: id);

        var dto = await base.UpdateAsync(id, input);

        if (input.IsPrimary)
        {
            await DemoteOtherPrimaryDepartmentsAsync(input.UserId, id);
        }

        return dto;
    }

    protected virtual async Task EnsureDepartmentAssignmentNotDuplicateAsync(Guid userId, Guid departmentId, Guid? excludedUserDepartmentId)
    {
        if (departmentId == default || userId == default)
        {
            return;
        }

        var queryable = await _userDepartmentRepository.GetQueryableAsync();
        var query = queryable.Where(x => x.UserId == userId && x.DepartmentId == departmentId);
        if (excludedUserDepartmentId.HasValue)
        {
            query = query.Where(x => x.Id != excludedUserDepartmentId.Value);
        }

        if (await AsyncExecuter.AnyAsync(query))
        {
            throw new UserFriendlyException(L["UserDepartmentDuplicateDepartment"]);
        }
    }

    protected virtual async Task DemoteOtherPrimaryDepartmentsAsync(Guid userId, Guid keepUserDepartmentId)
    {
        var queryable = await _userDepartmentRepository.GetQueryableAsync();
        var query = queryable.Where(x => x.UserId == userId && x.IsPrimary && x.Id != keepUserDepartmentId);
        var toDemote = await AsyncExecuter.ToListAsync(query);
        foreach (var ud in toDemote)
        {
            ud.IsPrimary = false;
            await _userDepartmentRepository.UpdateAsync(ud);
        }
    }
}
