using HC.Shared;
using HC.SurveySessions;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveyFiles;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;

namespace HC.SurveyFiles;

public class SurveyFilesAppService : SurveyFilesAppServiceBase, ISurveyFilesAppService
{
    //<suite-custom-code-autogenerated>
    protected ISurveyFileRepository _surveyFileRepository;

    public SurveyFilesAppService(ISurveyFileRepository surveyFileRepository, SurveyFileManager surveyFileManager, IDistributedCache<SurveyFileDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.SurveySessions.SurveySession, Guid> surveySessionRepository) : base(surveyFileRepository, surveyFileManager, downloadTokenCache, surveySessionRepository)
    {
        _surveyFileRepository = surveyFileRepository;
    }
    //</suite-custom-code-autogenerated>
    
    /// <summary>
    /// Public API to create survey file without authentication
    /// </summary>
    [AllowAnonymous]
    public virtual async Task<SurveyFileDto> CreatePublicSurveyFileAsync(SurveyFileCreateDto input)
    {
        var surveyFile = await _surveyFileManager.CreateAsync(
            input.SurveySessionId,
            input.UploaderType.ToString(),
            input.FileName,
            input.FilePath,
            input.FileSize,
            input.MimeType,
            input.FileType
        );

        await _surveyFileRepository.InsertAsync(surveyFile);
        return ObjectMapper.Map<SurveyFile, SurveyFileDto>(surveyFile);
    }
}