using HC.Shared;
using Volo.Abp.Identity;
using HC.WorkflowTemplates;
using HC.WorkflowStepTemplates;
using HC.Workflows;
using HC.Documents;
using HC.DocumentAssignments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.WorkflowStepAssignments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Notifications;
using HC.NotificationReceivers;
using Volo.Abp.EventBus.Distributed;
using static HC.Notifications.SourceType;
using static HC.Notifications.EventType;
using static HC.Notifications.RelatedType;

namespace HC.WorkflowStepAssignments;

public class WorkflowStepAssignmentsAppService : WorkflowStepAssignmentsAppServiceBase, IWorkflowStepAssignmentsAppService
{
    //<suite-custom-code-autogenerated>
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    // ISSUE-17 FIX: Removed shadowed fields _workflowStepTemplateRepository and _identityUserRepository.
    // These are already declared in the base class WorkflowStepAssignmentsAppServiceBase.
    // Declaring them again here would shadow the base class fields and could cause subtle bugs.
    protected IRepository<HC.DocumentAssignments.DocumentAssignment, Guid> _documentAssignmentRepository;
    protected IRepository<HC.Documents.Document, Guid> _documentRepository;
    
    public WorkflowStepAssignmentsAppService(
        IWorkflowStepAssignmentRepository workflowStepAssignmentRepository, 
        WorkflowStepAssignmentManager workflowStepAssignmentManager, 
        IDistributedCache<WorkflowStepAssignmentDownloadTokenCacheItem, string> downloadTokenCache, 
        IRepository<HC.WorkflowStepTemplates.WorkflowStepTemplate, Guid> workflowStepTemplateRepository, 
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository,
        IRepository<IdentityRole, Guid> identityRoleRepository,
        INotificationRepository notificationRepository,
        INotificationReceiverRepository notificationReceiverRepository,
        IDistributedEventBus distributedEventBus,
        IRepository<HC.DocumentAssignments.DocumentAssignment, Guid> documentAssignmentRepository,
        IRepository<HC.Documents.Document, Guid> documentRepository) 
        : base(workflowStepAssignmentRepository, workflowStepAssignmentManager, downloadTokenCache, workflowStepTemplateRepository, identityUserRepository, identityRoleRepository)
    {
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        // Base class fields are set via base(...) constructor call above
        _documentAssignmentRepository = documentAssignmentRepository;
        _documentRepository = documentRepository;
    }
    //</suite-custom-code-autogenerated>
    
    // Override CreateAsync to add notification logic
    public override async Task<WorkflowStepAssignmentDto> CreateAsync(WorkflowStepAssignmentCreateDto input)
    {
        // Call base method to create assignment
        var result = await base.CreateAsync(input);
        
        // Only send notification if DefaultUserId is provided
        if (input.DefaultUserId == null || input.DefaultUserId == Guid.Empty)
        {
            return result;
        }
        
        // Get step and user information
        var step = await _workflowStepTemplateRepository.GetAsync(input.StepId ?? Guid.Empty);
        var assignedUser = await _identityUserRepository.GetAsync(input.DefaultUserId.Value);
        var currentUser = CurrentUser;
        
        // Try to find a document assignment for this step to get document info
        // This is optional - if no document found, we'll just use step name
        Document? document = null;

        if (input.StepId.HasValue)
        {
            var documentAssignmentsQueryable = await _documentAssignmentRepository.GetQueryableAsync();
            var documentAssignment = documentAssignmentsQueryable
                .Where(x => x.WorkflowStepTemplateId == input.StepId)
                .FirstOrDefault();
            
            if (documentAssignment != null)
            {
                document = await _documentRepository.GetAsync(documentAssignment.DocumentId);
            }
        }
        
        return result;
    }
}