<Project Sdk="Microsoft.NET.Sdk.Web">
  
  
  <PropertyGroup><LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Volo.Abp.Elsa</RootNamespace>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Identity.Domain" VersionOverride="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Volo.Abp.Elsa.AspNetCore\Volo.Abp.Elsa.AspNetCore.csproj" />
    <ProjectReference Include="..\Volo.Abp.Elsa.Domain\Volo.Abp.Elsa.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elsa.Identity" />
  </ItemGroup>
</Project>
