using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.DocumentWorkflowInstanceFiles;

public class DocumentWorkflowInstanceFileManager : DocumentWorkflowInstanceFileManagerBase
{
    //<suite-custom-code-autogenerated>
    public DocumentWorkflowInstanceFileManager(IDocumentWorkflowInstanceFileRepository documentWorkflowInstanceFileRepository) : base(documentWorkflowInstanceFileRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}