using HC.DocumentFiles;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.DocumentWorkflowInstanceFiles;

public class DocumentWorkflowInstanceFile : DocumentWorkflowInstanceFileBase
{
    //<suite-custom-code-autogenerated>
    protected DocumentWorkflowInstanceFile()
    {
    }

    public DocumentWorkflowInstanceFile(Guid id, Guid documentWorkflowInstanceId, Guid documentFileId) : base(id, documentWorkflowInstanceId, documentFileId)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}