using HC.Shared;
using HC.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.Projects;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Logging;
using HC.CalendarEvents;

namespace HC.Projects;

public partial class ProjectsAppService : ProjectsAppServiceBase, IProjectsAppService
{
    //<suite-custom-code-autogenerated>
    protected ICalendarEventRepository _calendarEventRepository;

    public ProjectsAppService(
        IProjectRepository projectRepository,
        ProjectManager projectManager,
        IDistributedCache<ProjectDownloadTokenCacheItem, string> downloadTokenCache,
        IRepository<HC.Departments.Department, Guid> departmentRepository,
        ILogger<ProjectsAppServiceBase> logger,
        ICalendarEventRepository calendarEventRepository)
        : base(projectRepository, projectManager, downloadTokenCache, departmentRepository, logger)
    {
        _calendarEventRepository = calendarEventRepository;
    }
    //</suite-custom-code-autogenerated>

    // Override CreateAsync to add CalendarEvent for Project
    public override async Task<ProjectDto> CreateAsync(ProjectCreateDto input)
    {
        // Validate EndDate must not be before StartDate (allow same day)
        if (input.EndDate < input.StartDate)
        {
            throw new Volo.Abp.UserFriendlyException(L["EndDateMustNotBeBeforeStartDate"]);
        }

        // Call base method to create project
        var result = await base.CreateAsync(input);

        // Create CalendarEvent for the project
        var calendarEvent = new CalendarEvent(
            GuidGenerator.Create(),
            result.Name,
            DateTime.UtcNow,
            DateTime.UtcNow.AddYears(1), // Default end time (1 year from now)
            false, // AllDay
            EventType.TASK_ASSIGNED.ToString(),
            RelatedType.PROJECT.ToString(),
            EventVisibility.PUBLIC.ToString(),
            $"Project: {result.Name}",
            null,
            result.Id.ToString() // Store Project Id in RelatedId
        );

        calendarEvent.TenantId = CurrentTenant.Id;
        await _calendarEventRepository.InsertAsync(calendarEvent);

        return result;
    }

    public override async Task<ProjectDto> UpdateAsync(Guid id, ProjectUpdateDto input)
    {
        // Validate EndDate must not be before StartDate (allow same day)
        if (input.EndDate < input.StartDate)
        {
            throw new Volo.Abp.UserFriendlyException(L["EndDateMustNotBeBeforeStartDate"]);
        }

        return await base.UpdateAsync(id, input);
    }
}