<Project Sdk="Microsoft.NET.Sdk">
  
  
  <PropertyGroup><LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Volo.Abp.Elsa</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Volo.Abp.Elsa.Domain\Volo.Abp.Elsa.Domain.csproj" />
    <ProjectReference Include="..\Volo.Abp.Elsa.TestBase\Volo.Abp.Elsa.TestBase.csproj" />
  </ItemGroup>
</Project>