using HC.Shared;
using HC.DocumentFiles;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.DocumentWorkflowInstanceFiles;

namespace HC.DocumentWorkflowInstanceFiles;

public class DocumentWorkflowInstanceFilesAppService : DocumentWorkflowInstanceFilesAppServiceBase, IDocumentWorkflowInstanceFilesAppService
{
    //<suite-custom-code-autogenerated>
    public DocumentWorkflowInstanceFilesAppService(IDocumentWorkflowInstanceFileRepository documentWorkflowInstanceFileRepository, DocumentWorkflowInstanceFileManager documentWorkflowInstanceFileManager, IRepository<HC.DocumentFiles.DocumentFile, Guid> documentFileRepository) : base(documentWorkflowInstanceFileRepository, documentWorkflowInstanceFileManager, documentFileRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}