using System;
using Microsoft.AspNetCore.Authorization;
using HC.Permissions;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Caching;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp;
using HC.Notifications;
using HC.NotificationReceivers;
using HC.DocumentHistories;
using Volo.Abp.Identity;
using HC.UserDepartments;
using HC.DocumentAssignments;
using HC.WorkflowStepTemplates;
using HC.Departments;
using MiniExcelLibs;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Authorization;
using Volo.Abp.Content;
using HC.MasterDatas;
using HC.DocumentWorkflowInstances;
using HC.Shared;
using HC.DocumentFiles;
using HC.DocumentPdfViewer;
using Volo.Abp.BlobStoring;
using System.Text;

namespace HC.Documents;

public class DocumentsAppService : DocumentsAppServiceBase, IDocumentsAppService
{
    //<suite-custom-code-autogenerated>
    protected IDocumentHistoryRepository _documentHistoryRepository;
    protected DocumentHistoryManager _documentHistoryManager;
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    protected IRepository<HC.UserDepartments.UserDepartment, Guid> _userDepartmentRepository;
    protected IDocumentAssignmentRepository _documentAssignmentRepository;
    protected DocumentAssignmentManager _documentAssignmentManager;
    protected IRepository<IdentityUser, Guid> _identityUserRepository;
    protected IRepository<Department, Guid> _departmentRepository;
    protected IDocumentWorkflowInstanceRepository _documentWorkflowInstanceRepository;
    protected IRepository<DocumentFile, Guid> _documentFileRepository;
    protected IBlobContainer _blobContainer;
    protected IPdfStampingService _pdfStampingService;

    public DocumentsAppService(IDocumentRepository documentRepository, DocumentManager documentManager, IDistributedCache<DocumentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.MasterDatas.MasterData, Guid> masterDataRepository, IRepository<HC.Units.Unit, Guid> unitRepository, IRepository<HC.Workflows.Workflow, Guid> workflowRepository, ILogger<DocumentsAppServiceBase> logger, IDocumentHistoryRepository documentHistoryRepository, DocumentHistoryManager documentHistoryManager, INotificationRepository notificationRepository, INotificationReceiverRepository notificationReceiverRepository, IDistributedEventBus distributedEventBus, IRepository<HC.Documents.Document, Guid> documentRepository2, IRepository<HC.UserDepartments.UserDepartment, Guid> userDepartmentRepository, IDocumentAssignmentRepository documentAssignmentRepository, DocumentAssignmentManager documentAssignmentManager, IRepository<IdentityUser, Guid> identityUserRepository, IRepository<Department, Guid> departmentRepository, IDocumentWorkflowInstanceRepository documentWorkflowInstanceRepository, IRepository<DocumentFile, Guid> documentFileRepository, IBlobContainer blobContainer, IPdfStampingService pdfStampingService) : base(documentRepository, documentManager, downloadTokenCache, masterDataRepository, unitRepository, workflowRepository, logger)
    {
        _documentHistoryRepository = documentHistoryRepository;
        _documentHistoryManager = documentHistoryManager;
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        _userDepartmentRepository = userDepartmentRepository;
        _documentAssignmentRepository = documentAssignmentRepository;
        _documentAssignmentManager = documentAssignmentManager;
        _identityUserRepository = identityUserRepository;
        _departmentRepository = departmentRepository;
        _documentWorkflowInstanceRepository = documentWorkflowInstanceRepository;
        _documentFileRepository = documentFileRepository;
        _blobContainer = blobContainer;
        _pdfStampingService = pdfStampingService;
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...

    public virtual async Task<LookupDto<Guid>?> GetUnitLookupByIdAsync(Guid id)
    {
        var unit = await _unitRepository.FindAsync(id);
        return unit == null ? null : ObjectMapper.Map<HC.Units.Unit, LookupDto<Guid>>(unit);
    }

    public virtual async Task<bool> IsDocumentNumberDuplicateAsync(string no, Guid? excludeDocumentId = null)
    {
        var normalizedNo = no?.Trim();
        if (string.IsNullOrWhiteSpace(normalizedNo))
        {
            return false;
        }

        var normalizedNoLower = normalizedNo.ToLower();
        var query = await _documentRepository.GetQueryableAsync();

        return await AsyncExecuter.AnyAsync(
            query.Where(x => x.No != null)
                .WhereIf(excludeDocumentId.HasValue && excludeDocumentId.Value != Guid.Empty, x => x.Id != excludeDocumentId!.Value)
                .Where(x => x.No!.Trim().ToLower() == normalizedNoLower));
    }

    public virtual async Task<bool> IsStorageNumberDuplicateAsync(string storageNumber, Guid? excludeDocumentId = null)
    {
        var normalizedStorageNumber = storageNumber?.Trim();
        if (string.IsNullOrWhiteSpace(normalizedStorageNumber))
        {
            return false;
        }

        var normalizedStorageNumberLower = normalizedStorageNumber.ToLower();
        var query = await _documentRepository.GetQueryableAsync();

        return await AsyncExecuter.AnyAsync(
            query.Where(x => x.StorageNumber != null)
                .WhereIf(excludeDocumentId.HasValue && excludeDocumentId.Value != Guid.Empty, x => x.Id != excludeDocumentId!.Value)
                .Where(x => x.StorageNumber.Trim().ToLower() == normalizedStorageNumberLower));
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetIdentityUserLookupAsync(LookupRequestDto input)
    {
        var filter = input.Filter?.Trim();
        var query = await _identityUserRepository.GetQueryableAsync();

        if (!string.IsNullOrWhiteSpace(filter))
        {
            query = query.Where(x =>
                (x.UserName != null && x.UserName.Contains(filter)) ||
                (x.Name != null && x.Name.Contains(filter)) ||
                (x.Surname != null && x.Surname.Contains(filter)) ||
                (x.Email != null && x.Email.Contains(filter)));
        }

        var totalCount = await AsyncExecuter.CountAsync(query);
        var users = await AsyncExecuter.ToListAsync(
            query.OrderBy(x => x.Surname)
                 .ThenBy(x => x.Name)
                 .ThenBy(x => x.UserName)
                 .Skip(input.SkipCount)
                 .Take(input.MaxResultCount));

        return new PagedResultDto<LookupDto<Guid>>
        {
            TotalCount = totalCount,
            Items = users.Select(x => new LookupDto<Guid>
            {
                Id = x.Id,
                DisplayName = GetIdentityUserFullDisplayName(x)
            }).ToList()
        };
    }

    public override async Task<PagedResultDto<DocumentWithNavigationPropertiesDto>> GetListAsync(GetDocumentsInput input)
    {
        if (input.SourceType == DocumentSourceType.SentToMe)
        {
            var currentUserId = CurrentUser.Id;
            if (!currentUserId.HasValue)
            {
                return new PagedResultDto<DocumentWithNavigationPropertiesDto>
                {
                    TotalCount = 0,
                    Items = new List<DocumentWithNavigationPropertiesDto>()
                };
            }

            var sentToMeIds = await GetSentToMeDocumentIdsAsync(currentUserId.Value);
            if (sentToMeIds.Count == 0)
            {
                return new PagedResultDto<DocumentWithNavigationPropertiesDto>
                {
                    TotalCount = 0,
                    Items = new List<DocumentWithNavigationPropertiesDto>()
                };
            }

            var totalCount = await _documentRepository.GetCountAsync(
                input.FilterText,
                input.No,
                input.Title,
                input.CurrentStatus,
                input.CompletedTimeMin,
                input.CompletedTimeMax,
                input.StorageNumber,
                input.IncommingDateMin,
                input.IncommingDateMax,
                input.FieldId,
                input.UnitId,
                input.WorkflowId,
                input.StatusId,
                input.TypeId,
                input.UrgencyLevelId,
                input.SecrecyLevelId,
                sourceType: null,
                creatorId: null,
                sentToMeIds);

            var items = await _documentRepository.GetListWithNavigationPropertiesAsync(
                input.FilterText,
                input.No,
                input.Title,
                input.CurrentStatus,
                input.CompletedTimeMin,
                input.CompletedTimeMax,
                input.StorageNumber,
                input.IncommingDateMin,
                input.IncommingDateMax,
                input.FieldId,
                input.UnitId,
                input.WorkflowId,
                input.StatusId,
                input.TypeId,
                input.UrgencyLevelId,
                input.SecrecyLevelId,
                sourceType: null,
                creatorId: null,
                sentToMeIds,
                input.Sorting,
                input.MaxResultCount,
                input.SkipCount);

            var dtos = ObjectMapper.Map<List<DocumentWithNavigationProperties>, List<DocumentWithNavigationPropertiesDto>>(items);
            await PopulateSentToMeDisplayNamesAsync(dtos);
            await ApplySubmitSigningButtonVisibilityAsync(dtos);
            await ApplyPendingApprovalFlagsAsync(dtos);

            return new PagedResultDto<DocumentWithNavigationPropertiesDto>
            {
                TotalCount = totalCount,
                Items = dtos
            };
        }

        var page = await base.GetListAsync(input);
        await ApplySubmitSigningButtonVisibilityAsync(page.Items);
        await ApplyPendingApprovalFlagsAsync(page.Items);
        return page;
    }

    public override async Task<DocumentWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        var dto = await base.GetWithNavigationPropertiesAsync(id);
        await ApplySubmitSigningButtonVisibilityAsync(new List<DocumentWithNavigationPropertiesDto> { dto });
        await ApplyPendingApprovalFlagsAsync(new List<DocumentWithNavigationPropertiesDto> { dto });
        return dto;
    }

    /// <summary>
    /// Hide &quot;Submit for signing&quot; on parent rows when any workflow child has instance IN_PROGRESS or COMPLETED.
    /// Show again when only RETURNED, REJECTED, or CANCELLED (e.g. revoked / overdue cancel).
    /// </summary>
    private async Task ApplySubmitSigningButtonVisibilityAsync(IReadOnlyList<DocumentWithNavigationPropertiesDto>? items)
    {
        if (items == null || items.Count == 0)
        {
            return;
        }

        var parentIds = items
            .Where(i => i.Document.SourceType != DocumentSourceType.Workflow)
            .Select(i => i.Document.Id)
            .Distinct()
            .ToList();
        if (parentIds.Count == 0)
        {
            return;
        }

        var docQueryable = await _documentRepository.GetQueryableAsync();
        var instQueryable = await _documentWorkflowInstanceRepository.GetQueryableAsync();

        var childPairs = await AsyncExecuter.ToListAsync(
            docQueryable
                .Where(d => d.ParentDocumentId != null && parentIds.Contains(d.ParentDocumentId.Value))
                .Select(d => new { d.Id, ParentId = d.ParentDocumentId!.Value }));

        if (childPairs.Count == 0)
        {
            foreach (var item in items.Where(i => i.Document.SourceType != DocumentSourceType.Workflow))
            {
                item.HideSubmitForSigningButton = false;
            }

            return;
        }

        var childIds = childPairs.Select(x => x.Id).Distinct().ToList();

        var blockingChildIds = await AsyncExecuter.ToListAsync(
            instQueryable
                .Where(i => childIds.Contains(i.DocumentId) &&
                            (i.Status == nameof(DocumentWorkflowInstanceStatus.IN_PROGRESS) ||
                             i.Status == nameof(DocumentWorkflowInstanceStatus.COMPLETED)))
                .Select(i => i.DocumentId)
                .Distinct());

        var hideParentIds = childPairs
            .Where(p => blockingChildIds.Contains(p.Id))
            .Select(p => p.ParentId)
            .ToHashSet();

        foreach (var item in items.Where(i => i.Document.SourceType != DocumentSourceType.Workflow))
        {
            item.HideSubmitForSigningButton = hideParentIds.Contains(item.Document.Id);
        }
    }

    private async Task ApplyPendingApprovalFlagsAsync(IReadOnlyList<DocumentWithNavigationPropertiesDto>? items)
    {
        if (items == null || items.Count == 0 || !CurrentUser.Id.HasValue)
        {
            return;
        }

        var documentIds = items.Select(x => x.Document.Id).Distinct().ToList();
        if (documentIds.Count == 0)
        {
            return;
        }

        var processAction = DocumentAssignmentActionType.PROCESS.ToString();
        var assignmentQuery = await _documentAssignmentRepository.GetQueryableAsync();
        var pendingApprovalIds = await AsyncExecuter.ToListAsync(
            assignmentQuery.Where(x => documentIds.Contains(x.DocumentId)
                                       && x.WorkflowStepTemplateId == null
                                       && x.ActionType == processAction
                                       && x.Status == DocumentAssignmentStatus.PENDING.ToString()
                                       && x.IsCurrent
                                       && x.ReceiverUserId == CurrentUser.Id.Value)
                           .Select(x => x.DocumentId)
                           .Distinct());

        var pendingSet = pendingApprovalIds.ToHashSet();
        foreach (var item in items)
        {
            item.HasPendingApprovalTask = pendingSet.Contains(item.Document.Id);
        }
    }

    public override async Task<IRemoteStreamContent> GetListAsExcelFileAsync(DocumentExcelDownloadDto input)
    {
        if (input.SourceType == DocumentSourceType.SentToMe)
        {
            var currentUserId = CurrentUser.Id;
            if (currentUserId.HasValue)
            {
                var downloadToken = await _downloadTokenCache.GetAsync(input.DownloadToken);
                if (downloadToken == null || input.DownloadToken != downloadToken.Token)
                {
                    throw new AbpAuthorizationException("Invalid download token: " + input.DownloadToken);
                }

                var sentToMeIds = await GetSentToMeDocumentIdsAsync(currentUserId.Value);
                var documents = await _documentRepository.GetListWithNavigationPropertiesAsync(
                    input.FilterText,
                    input.No,
                    input.Title,
                    input.CurrentStatus,
                    input.CompletedTimeMin,
                    input.CompletedTimeMax,
                    input.StorageNumber,
                    input.IncommingDateMin,
                    input.IncommingDateMax,
                    input.FieldId,
                    input.UnitId,
                    input.WorkflowId,
                    input.StatusId,
                    input.TypeId,
                    input.UrgencyLevelId,
                    input.SecrecyLevelId,
                    sourceType: null,
                    creatorId: null,
                    sentToMeIds);

                var dtos = ObjectMapper.Map<List<DocumentWithNavigationProperties>, List<DocumentWithNavigationPropertiesDto>>(documents);
                await PopulateSentToMeDisplayNamesAsync(dtos);

                var items = dtos.Select(d => new
                {
                    No = d.Document.No,
                    Title = d.Document.Title,
                    FromUser = d.FromUserDisplayName,
                    Department = d.DepartmentDisplayName,
                    CurrentStatus = d.Document.CurrentStatus,
                    CompletedTime = d.Document.CompletedTime,
                    StorageNumber = d.Document.StorageNumber,
                    IncommingDate = d.Document.IncommingDate,
                    Field = d.Field?.Name,
                    Unit = d.Unit?.Name,
                    Workflow = d.Workflow?.Name,
                    Status = d.Status?.Name,
                    Type = d.Type?.Name,
                    UrgencyLevel = d.UrgencyLevel?.Name,
                    SecrecyLevel = d.SecrecyLevel?.Name
                });

                var memoryStream = new MemoryStream();
                await memoryStream.SaveAsAsync(items);
                memoryStream.Seek(0, SeekOrigin.Begin);
                return new RemoteStreamContent(memoryStream, "Documents.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            }
        }

        return await base.GetListAsExcelFileAsync(input);
    }

    /// <summary>
    /// Delete and revoke are only allowed for archive documents (SourceType = Archive, menu sourceType = 0).
    /// </summary>
    private void EnsureArchiveDocumentForDeleteOrRevoke(Document document)
    {
        if (document.SourceType != DocumentSourceType.Archive)
        {
            throw new UserFriendlyException(L["DeleteRevokeOnlyInArchiveView"]);
        }
    }

    [Authorize(HCPermissions.Documents.Delete)]
    public override async Task DeleteAsync(Guid id)
    {
        var document = await _documentRepository.GetAsync(id);
        EnsureArchiveDocumentForDeleteOrRevoke(document);
        await base.DeleteAsync(id);
    }

    [Authorize(HCPermissions.Documents.Delete)]
    public override async Task DeleteByIdsAsync(List<Guid> documentIds)
    {
        if (documentIds == null || documentIds.Count == 0)
        {
            return;
        }

        var distinctIds = documentIds.Distinct().ToList();
        var documents = await _documentRepository.GetListAsync(d => distinctIds.Contains(d.Id));
        if (documents.Count != distinctIds.Count)
        {
            throw new UserFriendlyException(L["DocumentNotFound"]);
        }

        foreach (var document in documents)
        {
            EnsureArchiveDocumentForDeleteOrRevoke(document);
        }

        await base.DeleteByIdsAsync(documentIds);
    }

    [Authorize(HCPermissions.Documents.Delete)]
    public override async Task DeleteAllAsync(GetDocumentsInput input)
    {
        if (input.SourceType != DocumentSourceType.Archive)
        {
            throw new UserFriendlyException(L["DeleteRevokeOnlyInArchiveView"]);
        }

        await base.DeleteAllAsync(input);
    }

    /// <summary>
    /// Inbox document IDs: non-workflow VIEW assignments to current user, plus explicit SentToMe rows (user or department).
    /// </summary>
    private async Task<List<Guid>> GetSentToMeDocumentIdsAsync(Guid userId)
    {
        var assignmentQ = await _documentAssignmentRepository.GetQueryableAsync();
        var docQ = await _documentRepository.GetQueryableAsync();
        var viewAction = DocumentAssignmentActionType.VIEW.ToString();
        var processAction = DocumentAssignmentActionType.PROCESS.ToString();

        var fromAssignmentsQuery = assignmentQ
            .Where(a => a.ReceiverUserId == userId
                        && a.WorkflowStepTemplateId == null
                        && a.IsCurrent
                        && ((a.ActionType == viewAction
                             && a.Status != nameof(DocumentAssignmentStatus.REVOKE))
                            || (a.ActionType == processAction
                                && a.Status == nameof(DocumentAssignmentStatus.PENDING))))
            .Join(docQ.Where(d => d.SourceType != DocumentSourceType.Workflow),
                a => a.DocumentId,
                d => d.Id,
                (_, d) => d.Id)
            .Distinct();

        var fromAssignments = await AsyncExecuter.ToListAsync(fromAssignmentsQuery);

        var userDepts = await _userDepartmentRepository.GetListAsync(ud => ud.UserId == userId && ud.IsActive);
        var deptIds = userDepts.Select(ud => ud.DepartmentId).Distinct().ToList();

        IQueryable<Guid> explicitQuery = docQ
            .Where(d => d.SourceType == DocumentSourceType.SentToMe
                        && (d.ReceiverUserId == userId
                            || (d.DepartmentId != null && deptIds.Contains(d.DepartmentId.Value))))
            .Select(d => d.Id);

        var fromExplicit = await AsyncExecuter.ToListAsync(explicitQuery);

        return fromAssignments.Union(fromExplicit).Distinct().ToList();
    }

    /// <summary>
    /// Prefer Name + Surname (full name); fall back to UserName / Email.
    /// </summary>
    private static string GetIdentityUserFullDisplayName(IdentityUser user)
    {
        var parts = new[] { user.Surname, user.Name }.Where(s => !string.IsNullOrWhiteSpace(s));
        var full = string.Join(' ', parts).Trim();
        return string.IsNullOrWhiteSpace(full)
            ? (user.UserName ?? user.Email ?? user.Id.ToString())
            : full;
    }

    private async Task PopulateSentToMeDisplayNamesAsync(List<DocumentWithNavigationPropertiesDto> dtos)
    {
        if (dtos.Count == 0)
        {
            return;
        }

        var userIds = dtos
            .Select(d => d.Document.FromUserId ?? d.Document.CreatorId)
            .Where(id => id.HasValue)
            .Select(id => id!.Value)
            .Distinct()
            .ToList();

        List<IdentityUser> users;
        if (userIds.Count > 0)
        {
            var userQ = (await _identityUserRepository.GetQueryableAsync()).Where(u => userIds.Contains(u.Id));
            users = await AsyncExecuter.ToListAsync(userQ);
        }
        else
        {
            users = new List<IdentityUser>();
        }

        var userDict = users.ToDictionary(u => u.Id, GetIdentityUserFullDisplayName);

        var deptIds = dtos
            .Select(d => d.Document.DepartmentId)
            .Where(id => id.HasValue)
            .Select(id => id!.Value)
            .Distinct()
            .ToList();

        var depts = deptIds.Count > 0
            ? await _departmentRepository.GetListAsync(d => deptIds.Contains(d.Id))
            : new List<Department>();

        var deptDict = depts.ToDictionary(d => d.Id, d => d.Name ?? d.Id.ToString());

        foreach (var dto in dtos)
        {
            var fromUserId = dto.Document.FromUserId ?? dto.Document.CreatorId;
            if (fromUserId.HasValue && userDict.TryGetValue(fromUserId.Value, out var fn))
            {
                dto.FromUserDisplayName = fn;
            }

            if (dto.Document.DepartmentId.HasValue && deptDict.TryGetValue(dto.Document.DepartmentId.Value, out var dn))
            {
                dto.DepartmentDisplayName = dn;
            }
        }
    }

    public async Task<bool> SendDocumentAsync(SendDocumentInput input)
    {
        try
        {
            _logger.LogInformation("SendDocumentAsync started: DocumentId={DocumentId}, Recipients={RecipientCount}, Departments={DepartmentCount}",
                input.DocumentId,
                input.Recipients?.Count ?? 0,
                input.Departments?.Count ?? 0);

            // Validate input
            if (input.DocumentId == Guid.Empty)
            {
                throw new UserFriendlyException(L["DocumentId is required"]);
            }

            if ((input.Recipients == null || input.Recipients.Count == 0) &&
                (input.Departments == null || input.Departments.Count == 0))
            {
                throw new UserFriendlyException(L["At least one recipient or department is required"]);
            }

            // Get current user
            var currentUserId = CurrentUser.Id;
            if (currentUserId == null)
            {
                throw new UserFriendlyException(L["User not authenticated"]);
            }

            // Get document info
            var document = await _documentRepository.GetAsync(input.DocumentId);

            var allReceiverUserIds = new HashSet<Guid>();

            if (input.Recipients != null)
            {
                foreach (var id in input.Recipients)
                {
                    allReceiverUserIds.Add(id);
                }
            }

            if (input.Departments != null && input.Departments.Count > 0)
            {
                var departmentIds = input.Departments.Distinct().ToList();
                var userDepartments = await _userDepartmentRepository.GetListAsync(ud =>
                    departmentIds.Contains(ud.DepartmentId) && ud.IsActive);
                foreach (var ud in userDepartments)
                {
                    allReceiverUserIds.Add(ud.UserId);
                }
            }

            if (allReceiverUserIds.Count == 0)
            {
                throw new UserFriendlyException(L["No valid recipients found"]);
            }

            var receiverList = allReceiverUserIds.ToList();
            _logger.LogInformation("Sending document to {RecipientCount} recipients", receiverList.Count);

            var viewAction = DocumentAssignmentActionType.VIEW.ToString();
            var assignmentQueryable = await _documentAssignmentRepository.GetQueryableAsync();
            var existingInboxAssignments = await AsyncExecuter.ToListAsync(
                assignmentQueryable
                    .Where(a => a.DocumentId == input.DocumentId
                                && receiverList.Contains(a.ReceiverUserId)
                                && a.ActionType == viewAction
                                && a.WorkflowStepTemplateId == null
                                && a.IsCurrent
                                && a.Status != nameof(DocumentAssignmentStatus.REVOKE))
                    .OrderByDescending(a => a.CreationTime));
            var existingInboxAssignmentByReceiver = existingInboxAssignments
                .GroupBy(a => a.ReceiverUserId)
                .ToDictionary(g => g.Key, g => g.First());

            // Create notification (ICurrentUser has Name / UserName; no Surname on interface)
            var userFullName = !string.IsNullOrWhiteSpace(CurrentUser.Name)
                ? CurrentUser.Name!
                : (CurrentUser.UserName ?? L["System"]);
            var notificationTitleKey = "DocumentReceived";
            var notificationContentKey = $"DocumentReceivedMessage|{document.StorageNumber}|{document.Title}|{userFullName ?? L["System"]}";

            var notification = new Notification(
                GuidGenerator.Create(),
                notificationTitleKey,
                notificationContentKey,
                SourceType.DOCUMENT.ToString(),
                EventType.DOCUMENT_SENT.ToString(),
                RelatedType.DOCUMENT.ToString(),
                "NORMAL",
                document.Id.ToString()
            );

            notification.TenantId = CurrentTenant.Id;
            await _notificationRepository.InsertAsync(notification);

            var now = Clock.Now; // ISSUE-18 FIX: Use ABP Clock instead of DateTime.Now
            var historyComment = $"Document sent from user {CurrentUser.UserName ?? L["System"]}";

            var notificationReceivers = receiverList.Select(receiverUserId =>
            {
                var nr = new NotificationReceiver(GuidGenerator.Create(), notification.Id, receiverUserId, false);
                nr.TenantId = CurrentTenant.Id;
                return nr;
            }).ToList();

            await _notificationReceiverRepository.InsertManyAsync(notificationReceivers);

            var documentHistories = receiverList.Select(receiverUserId =>
            {
                var dh = new DocumentHistory(
                    GuidGenerator.Create(),
                    input.DocumentId,
                    currentUserId,
                    receiverUserId,
                    nameof(DocumentHistoryAction.TRINH),
                    historyComment);
                dh.TenantId = CurrentTenant.Id;
                return dh;
            }).ToList();

            await _documentHistoryRepository.InsertManyAsync(documentHistories);

            var assignmentsToUpdate = new List<DocumentAssignment>();
            var assignmentsToInsert = new List<DocumentAssignment>();

            foreach (var receiverUserId in receiverList)
            {
                if (existingInboxAssignmentByReceiver.TryGetValue(receiverUserId, out var existingAssignment))
                {
                    existingAssignment.Status = DocumentAssignmentStatus.DONE.ToString();
                    existingAssignment.ProcessedAt = now;
                    existingAssignment.IsCurrent = true;
                    assignmentsToUpdate.Add(existingAssignment);
                }
                else
                {
                    var documentAssignment = new DocumentAssignment(
                        GuidGenerator.Create(),
                        input.DocumentId,
                        null,
                        receiverUserId,
                        (int)DocumentAssignmentStepOrder.ORIGINAL,
                        DocumentAssignmentActionType.VIEW.ToString(),
                        DocumentAssignmentStatus.DONE.ToString(),
                        now,
                        now,
                        true);
                    documentAssignment.TenantId = CurrentTenant.Id;
                    assignmentsToInsert.Add(documentAssignment);
                }
            }

            if (assignmentsToUpdate.Count > 0)
            {
                await _documentAssignmentRepository.UpdateManyAsync(assignmentsToUpdate);
            }

            if (assignmentsToInsert.Count > 0)
            {
                await _documentAssignmentRepository.InsertManyAsync(assignmentsToInsert);
            }

            _logger.LogInformation(
                "SendDocumentAsync assignments: updated={UpdatedCount}, inserted={InsertedCount}",
                assignmentsToUpdate.Count,
                assignmentsToInsert.Count);

            await _distributedEventBus.PublishAsync(
                new NotificationCreatedEto
                {
                    NotificationId = notification.Id,
                    ReceiverUserIds = receiverList
                }
            );

            _logger.LogInformation("SendDocumentAsync completed successfully: DocumentId={DocumentId}, SentTo={RecipientCount} users",
                input.DocumentId, receiverList.Count);

            // Denormalized routing metadata for SentToMe grid (From / Receiver / Department)
            document.FromUserId = currentUserId.Value;
            if (input.Recipients?.Count == 1 && (input.Departments == null || input.Departments.Count == 0))
            {
                document.ReceiverUserId = input.Recipients[0];
                document.DepartmentId = null;
            }
            else if (input.Departments?.Count == 1 && (input.Recipients == null || input.Recipients.Count == 0))
            {
                document.DepartmentId = input.Departments[0];
                document.ReceiverUserId = null;
            }
            else
            {
                document.ReceiverUserId = null;
                document.DepartmentId = null;
            }

            await _documentRepository.UpdateAsync(document);

            // Update document status to DA_GUI (Đã gửi) after successfully sending
            await UpdateDocumentStatusAsync(input.DocumentId, DocumentStatusCode.DA_GUI);

            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in SendDocumentAsync: DocumentId={DocumentId}", input.DocumentId);
            throw;
        }
    }

    public async Task<bool> RevokeDocumentAsync(RevokeDocumentInput input)
    {
        try
        {
            _logger.LogInformation("RevokeDocumentAsync started: DocumentId={DocumentId}", input.DocumentId);

            // Validate input
            if (input.DocumentId == Guid.Empty)
            {
                throw new UserFriendlyException(L["DocumentId is required"]);
            }

            // Get current user
            var currentUserId = CurrentUser.Id;
            if (currentUserId == null)
            {
                throw new UserFriendlyException(L["User not authenticated"]);
            }

            // Get document info
            var document = await _documentRepository.GetAsync(input.DocumentId);
            EnsureArchiveDocumentForDeleteOrRevoke(document);

            var assignmentQueryable = await _documentAssignmentRepository.GetQueryableAsync();
            var viewAction = DocumentAssignmentActionType.VIEW.ToString();
            var documentAssignments = await AsyncExecuter.ToListAsync(
                assignmentQueryable.Where(a =>
                    a.DocumentId == input.DocumentId
                    && a.ActionType == viewAction
                    && a.WorkflowStepTemplateId == null));

            if (documentAssignments == null || documentAssignments.Count == 0)
            {
                _logger.LogWarning("No document assignments found for DocumentId={DocumentId}", input.DocumentId);
                return true;
            }

            // Get all unique receiver user IDs
            var receiverUserIds = documentAssignments
                .Select(da => da.ReceiverUserId)
                .Distinct()
                .ToList();

            _logger.LogInformation("Revoking document from {RecipientCount} recipients", receiverUserIds.Count);

            foreach (var documentAssignment in documentAssignments)
            {
                documentAssignment.Status = DocumentAssignmentStatus.REVOKE.ToString();
                documentAssignment.IsCurrent = false;
            }

            await _documentAssignmentRepository.UpdateManyAsync(documentAssignments);

            // Create notification
            var notificationTitleKey = "DocumentRevoked";
            var notificationContentKey = $"DocumentRevokedMessage|{document.StorageNumber}|{document.Title}|{CurrentUser.UserName ?? L["System"]}";

            var notification = new Notification(
                GuidGenerator.Create(),
                notificationTitleKey,
                notificationContentKey,
                SourceType.DOCUMENT.ToString(),
                EventType.DOCUMENT_REVOKED.ToString(),
                RelatedType.DOCUMENT.ToString(),
                "NORMAL",
                document.Id.ToString()
            );

            notification.TenantId = CurrentTenant.Id;
            await _notificationRepository.InsertAsync(notification);

            var revokeHistoryComment = $"Revoked document {document.Title} by {CurrentUser.UserName ?? L["System"]}";
            var notificationReceivers = receiverUserIds.Select(receiverUserId =>
            {
                var nr = new NotificationReceiver(GuidGenerator.Create(), notification.Id, receiverUserId, false);
                nr.TenantId = CurrentTenant.Id;
                return nr;
            }).ToList();
            await _notificationReceiverRepository.InsertManyAsync(notificationReceivers);

            var revokeHistories = receiverUserIds.Select(receiverUserId =>
            {
                var dh = new DocumentHistory(
                    GuidGenerator.Create(),
                    input.DocumentId,
                    currentUserId,
                    receiverUserId,
                    "THU_HOI",
                    revokeHistoryComment);
                dh.TenantId = CurrentTenant.Id;
                return dh;
            }).ToList();
            await _documentHistoryRepository.InsertManyAsync(revokeHistories);

            // Publish event to RabbitMQ for real-time notification
            await _distributedEventBus.PublishAsync(
                new NotificationCreatedEto
                {
                    NotificationId = notification.Id,
                    ReceiverUserIds = receiverUserIds
                }
            );

            _logger.LogInformation("RevokeDocumentAsync completed successfully: DocumentId={DocumentId}, RevokedFrom={RecipientCount} users",
                input.DocumentId, receiverUserIds.Count.ToString());

            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in RevokeDocumentAsync: DocumentId={DocumentId}", input.DocumentId);
            throw;
        }
    }

    [Authorize(HCPermissions.Documents.SubmitForApproval)]
    public async Task<bool> SubmitForApprovalAsync(SubmitDocumentForApprovalInput input)
    {
        if (input.DocumentId == Guid.Empty || input.LeaderUserId == Guid.Empty)
        {
            throw new UserFriendlyException(L["DocumentId is required"]);
        }

        var currentUserId = CurrentUser.Id ?? throw new UserFriendlyException(L["User not authenticated"]);
        var document = await _documentRepository.GetAsync(input.DocumentId);
        EnsureArchiveDocumentForDeleteOrRevoke(document);

        var leader = await _identityUserRepository.FindAsync(input.LeaderUserId);
        if (leader == null)
        {
            throw new UserFriendlyException("Leader user not found.");
        }

        var assignmentQuery = await _documentAssignmentRepository.GetQueryableAsync();
        var processAction = DocumentAssignmentActionType.PROCESS.ToString();
        var existingAssignments = await AsyncExecuter.ToListAsync(
            assignmentQuery.Where(x => x.DocumentId == input.DocumentId
                                       && x.WorkflowStepTemplateId == null
                                       && x.ActionType == processAction));

        foreach (var a in existingAssignments)
        {
            a.IsCurrent = false;
            if (a.Status == DocumentAssignmentStatus.PENDING.ToString())
            {
                a.Status = DocumentAssignmentStatus.REVOKE.ToString();
                a.ProcessedAt = DateTime.Now;
            }
        }

        if (existingAssignments.Count > 0)
        {
            await _documentAssignmentRepository.UpdateManyAsync(existingAssignments);
        }

        var approvalAssignment = new DocumentAssignment(
            GuidGenerator.Create(),
            input.DocumentId,
            null,
            input.LeaderUserId,
            (int)DocumentAssignmentStepOrder.ORIGINAL,
            processAction,
            DocumentAssignmentStatus.PENDING.ToString(),
            DateTime.Now,
            DateTime.Now,
            true);
        approvalAssignment.TenantId = CurrentTenant.Id;
        await _documentAssignmentRepository.InsertAsync(approvalAssignment);

        document.FromUserId = currentUserId;
        document.ReceiverUserId = input.LeaderUserId;
        document.DepartmentId = null;
        await _documentRepository.UpdateAsync(document);

        await UpdateDocumentStatusAsync(input.DocumentId, DocumentStatusCode.CHO_PHE_DUYET);

        var historyComment = string.IsNullOrWhiteSpace(input.Message)
            ? "Van thu gui van ban toi lanh dao de phe duyet."
            : input.Message!;

        var history = new DocumentHistory(
            GuidGenerator.Create(),
            input.DocumentId,
            currentUserId,
            input.LeaderUserId,
            DocumentStatusCode.CHO_PHE_DUYET.GetCode(),
            historyComment);
        history.TenantId = CurrentTenant.Id;
        await _documentHistoryRepository.InsertAsync(history);

        var notification = new Notification(
            GuidGenerator.Create(),
            "DocumentApprovalRequested",
            $"DocumentApprovalRequestedMessage|{document.StorageNumber}|{document.Title}|{CurrentUser.UserName ?? "System"}",
            SourceType.DOCUMENT.ToString(),
            EventType.DOCUMENT_SENT.ToString(),
            RelatedType.DOCUMENT.ToString(),
            "NORMAL",
            document.Id.ToString());
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);

        var receiver = new NotificationReceiver(GuidGenerator.Create(), notification.Id, input.LeaderUserId, false)
        {
            TenantId = CurrentTenant.Id
        };
        await _notificationReceiverRepository.InsertAsync(receiver);
        await _distributedEventBus.PublishAsync(new NotificationCreatedEto
        {
            NotificationId = notification.Id,
            ReceiverUserIds = new List<Guid> { input.LeaderUserId }
        });

        return true;
    }

    [Authorize(HCPermissions.Documents.RejectApproval)]
    public async Task<bool> RejectApprovalAsync(RejectDocumentApprovalInput input)
    {
        if (input.DocumentId == Guid.Empty || string.IsNullOrWhiteSpace(input.Reason))
        {
            throw new UserFriendlyException("DocumentId and reject reason are required.");
        }

        var currentUserId = CurrentUser.Id ?? throw new UserFriendlyException(L["User not authenticated"]);
        var (document, assignment) = await GetPendingApprovalAssignmentAsync(input.DocumentId, currentUserId);

        assignment.Status = DocumentAssignmentStatus.REJECTED.ToString();
        assignment.ProcessedAt = DateTime.Now;
        assignment.IsCurrent = false;
        await _documentAssignmentRepository.UpdateAsync(assignment);

        await UpdateDocumentStatusAsync(input.DocumentId, DocumentStatusCode.TU_CHOI);

        var history = new DocumentHistory(
            GuidGenerator.Create(),
            input.DocumentId,
            currentUserId,
            document.CreatorId.Value,
            DocumentStatusCode.TU_CHOI.GetCode(),
            input.Reason.Trim());
        history.TenantId = CurrentTenant.Id;
        await _documentHistoryRepository.InsertAsync(history);

        await NotifyDocumentOwnerAsync(document, "DocumentApprovalRejected", $"DocumentApprovalRejectedMessage|{document.StorageNumber}|{document.Title}|{CurrentUser.UserName ?? "System"}");
        return true;
    }

    [Authorize(HCPermissions.Documents.ApproveWithNote)]
    public async Task<bool> ApproveWithNoteAsync(ApproveDocumentWithNoteInput input)
    {
        if (input.DocumentId == Guid.Empty || input.PageNumber <= 0 || string.IsNullOrWhiteSpace(input.NoteContent))
        {
            throw new UserFriendlyException("DocumentId, page number and note content are required.");
        }

        var currentUserId = CurrentUser.Id ?? throw new UserFriendlyException(L["User not authenticated"]);
        var (document, assignment) = await GetPendingApprovalAssignmentAsync(input.DocumentId, currentUserId);

        var latestPdfFile = await GetLatestPdfFileAsync(input.DocumentId);
        if (latestPdfFile == null || string.IsNullOrWhiteSpace(latestPdfFile.Path))
        {
            throw new UserFriendlyException("PDF file for this document was not found.");
        }

        var originalBytes = await _blobContainer.GetAllBytesOrNullAsync(latestPdfFile.Path!);
        if (originalBytes == null || originalBytes.Length == 0)
        {
            throw new UserFriendlyException("Could not load PDF bytes from storage.");
        }

        var stamped = _pdfStampingService.AddTextNote(
            originalBytes,
            input.PageNumber,
            input.PdfX,
            input.PdfY,
            input.NoteContent);

        var approvedBlobPath = $"documents/approved/{input.DocumentId}/{GuidGenerator.Create():N}.pdf";
        await _blobContainer.SaveAsync(approvedBlobPath, stamped, overrideExisting: true);

        var approvedFile = new DocumentFile(
            GuidGenerator.Create(),
            input.DocumentId,
            BuildApprovedFileName(latestPdfFile.Name),
            true,
            DateTime.Now,
            approvedBlobPath,
            ComputeHash(stamped))
        {
            TenantId = CurrentTenant.Id
        };
        await _documentFileRepository.InsertAsync(approvedFile);

        assignment.Status = DocumentAssignmentStatus.DONE.ToString();
        assignment.ProcessedAt = DateTime.Now;
        assignment.IsCurrent = false;
        await _documentAssignmentRepository.UpdateAsync(assignment);

        await UpdateDocumentStatusAsync(input.DocumentId, DocumentStatusCode.DA_PHE_DUYET);

        var approvalComment = $"[Page:{input.PageNumber}; X:{input.PdfX:0.##}; Y:{input.PdfY:0.##}] {input.NoteContent.Trim()}";
        var history = new DocumentHistory(
            GuidGenerator.Create(),
            input.DocumentId,
            currentUserId,
            document.CreatorId.Value,
            DocumentStatusCode.DA_PHE_DUYET.GetCode(),
            approvalComment);
        history.TenantId = CurrentTenant.Id;
        await _documentHistoryRepository.InsertAsync(history);

        await NotifyDocumentOwnerAsync(document, "DocumentApproved", $"DocumentApprovedMessage|{document.StorageNumber}|{document.Title}|{CurrentUser.UserName ?? "System"}");
        return true;
    }

    private async Task<(Document Document, DocumentAssignment Assignment)> GetPendingApprovalAssignmentAsync(Guid documentId, Guid currentUserId)
    {
        var document = await _documentRepository.GetAsync(documentId);
        EnsureArchiveDocumentForDeleteOrRevoke(document);

        var processAction = DocumentAssignmentActionType.PROCESS.ToString();
        var assignmentQuery = await _documentAssignmentRepository.GetQueryableAsync();
        var assignment = await AsyncExecuter.FirstOrDefaultAsync(
            assignmentQuery.Where(x => x.DocumentId == documentId
                                       && x.WorkflowStepTemplateId == null
                                       && x.ActionType == processAction
                                       && x.Status == DocumentAssignmentStatus.PENDING.ToString()
                                       && x.IsCurrent
                                       && x.ReceiverUserId == currentUserId)
                           .OrderByDescending(x => x.CreationTime));

        if (assignment == null)
        {
            throw new UserFriendlyException("You do not have a pending approval task for this document.");
        }

        return (document, assignment);
    }

    private async Task<DocumentFile?> GetLatestPdfFileAsync(Guid documentId)
    {
        var fileQuery = await _documentFileRepository.GetQueryableAsync();
        return await AsyncExecuter.FirstOrDefaultAsync(
            fileQuery.Where(x => x.DocumentId == documentId
                              && x.Path != null
                              && (x.Path.EndsWith(".pdf") || x.Name.EndsWith(".pdf")))
                     .OrderByDescending(x => x.UploadedAt));
    }

    private static string BuildApprovedFileName(string originalName)
    {
        var safeOriginal = string.IsNullOrWhiteSpace(originalName) ? "document.pdf" : originalName;
        var ext = Path.GetExtension(safeOriginal);
        var name = Path.GetFileNameWithoutExtension(safeOriginal);
        return $"{name}-approved-{DateTime.Now:yyyyMMddHHmmss}{(string.IsNullOrWhiteSpace(ext) ? ".pdf" : ext)}";
    }

    private static string ComputeHash(byte[] content)
    {
        using var sha = System.Security.Cryptography.SHA256.Create();
        var hashBytes = sha.ComputeHash(content);
        var sb = new StringBuilder(hashBytes.Length * 2);
        foreach (var b in hashBytes)
        {
            sb.Append(b.ToString("x2"));
        }

        return sb.ToString();
    }

    private async Task NotifyDocumentOwnerAsync(Document document, string titleKey, string contentKey)
    {
        if (!document.CreatorId.HasValue || document.CreatorId.Value == Guid.Empty)
        {
            return;
        }

        var notification = new Notification(
            GuidGenerator.Create(),
            titleKey,
            contentKey,
            SourceType.DOCUMENT.ToString(),
            EventType.WORKFLOW_ACTION.ToString(),
            RelatedType.DOCUMENT.ToString(),
            "NORMAL",
            document.Id.ToString())
        {
            TenantId = CurrentTenant.Id
        };

        await _notificationRepository.InsertAsync(notification);
        var receiver = new NotificationReceiver(GuidGenerator.Create(), notification.Id, document.CreatorId.Value, false)
        {
            TenantId = CurrentTenant.Id
        };
        await _notificationReceiverRepository.InsertAsync(receiver);
        await _distributedEventBus.PublishAsync(new NotificationCreatedEto
        {
            NotificationId = notification.Id,
            ReceiverUserIds = new List<Guid> { document.CreatorId.Value }
        });
    }

    /// <summary>
    /// Update document status by DocumentStatusCode enum.
    /// Looks up MasterData by Code and Type = "TRANG_THAI_VB".
    /// </summary>
    private async Task UpdateDocumentStatusAsync(Guid documentId, DocumentStatusCode statusCode)
    {
        try
        {
            var document = await _documentRepository.GetAsync(documentId);
            var code = statusCode.GetCode();

            var statusQuery = (await _masterDataRepository.GetQueryableAsync())
                .Where(x => x.Code == code && x.Type == MasterDataType.Status.GetTypeValue());
            var status = await AsyncExecuter.FirstOrDefaultAsync(statusQuery);
            if (status == null)
            {
                _logger.LogWarning("MasterData with Code='{Code}' and Type='TRANG_THAI_VB' not found. Document status will not be updated.", code);
                return;
            }

            document.StatusId = status.Id;
            await _documentRepository.UpdateAsync(document);

            _logger.LogInformation("Document status updated to {Code}: DocumentId={DocumentId}, StatusId={StatusId}",
                code, documentId, status.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error updating document status to {Code}: DocumentId={DocumentId}",
                statusCode.GetCode(), documentId);
            // Don't throw - we don't want to fail the parent operation if status update fails
        }
    }
}
