using System;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Caching;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using Volo.Abp.EventBus.Distributed;
using Volo.Abp;
using HC.Notifications;
using HC.NotificationReceivers;
using HC.DocumentHistories;
using Volo.Abp.Identity;
using HC.UserDepartments;
using HC.DocumentAssignments;
using HC.WorkflowStepTemplates;
using MiniExcelLibs;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Authorization;
using Volo.Abp.Content;
using HC.MasterDatas;

namespace HC.Documents;

public class DocumentsAppService : DocumentsAppServiceBase, IDocumentsAppService
{
    //<suite-custom-code-autogenerated>
    protected IDocumentHistoryRepository _documentHistoryRepository;
    protected DocumentHistoryManager _documentHistoryManager;
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    protected IRepository<HC.UserDepartments.UserDepartment, Guid> _userDepartmentRepository;
    protected IDocumentAssignmentRepository _documentAssignmentRepository;
    protected DocumentAssignmentManager _documentAssignmentManager;

    public DocumentsAppService(IDocumentRepository documentRepository, DocumentManager documentManager, IDistributedCache<DocumentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.MasterDatas.MasterData, Guid> masterDataRepository, IRepository<HC.Units.Unit, Guid> unitRepository, IRepository<HC.Workflows.Workflow, Guid> workflowRepository, ILogger<DocumentsAppServiceBase> logger, IDocumentHistoryRepository documentHistoryRepository, DocumentHistoryManager documentHistoryManager, INotificationRepository notificationRepository, INotificationReceiverRepository notificationReceiverRepository, IDistributedEventBus distributedEventBus, IRepository<HC.Documents.Document, Guid> documentRepository2, IRepository<HC.UserDepartments.UserDepartment, Guid> userDepartmentRepository, IDocumentAssignmentRepository documentAssignmentRepository, DocumentAssignmentManager documentAssignmentManager) : base(documentRepository, documentManager, downloadTokenCache, masterDataRepository, unitRepository, workflowRepository, logger)
    {
        _documentHistoryRepository = documentHistoryRepository;
        _documentHistoryManager = documentHistoryManager;
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        _userDepartmentRepository = userDepartmentRepository;
        _documentAssignmentRepository = documentAssignmentRepository;
        _documentAssignmentManager = documentAssignmentManager;
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
    public override async Task<PagedResultDto<DocumentWithNavigationPropertiesDto>> GetListAsync(GetDocumentsInput input)
    {
        if (input.SourceType == DocumentSourceType.Personal)
        {
            var currentUserId = CurrentUser.Id;
            if (currentUserId.HasValue)
            {
                var assignedDocumentIds = await GetAssignedDocumentIdsAsync(currentUserId.Value);

                var totalCount = await _documentRepository.GetCountAsync(
                    input.FilterText,
                    input.No,
                    input.Title,
                    input.CurrentStatus,
                    input.CompletedTimeMin,
                    input.CompletedTimeMax,
                    input.StorageNumber,
                    input.IncommingDateMin,
                    input.IncommingDateMax,
                    input.FieldId,
                    input.UnitId,
                    input.WorkflowId,
                    input.StatusId,
                    input.TypeId,
                    input.UrgencyLevelId,
                    input.SecrecyLevelId,
                    input.SourceType,
                    currentUserId.Value,
                    assignedDocumentIds);

                var items = await _documentRepository.GetListWithNavigationPropertiesAsync(
                    input.FilterText,
                    input.No,
                    input.Title,
                    input.CurrentStatus,
                    input.CompletedTimeMin,
                    input.CompletedTimeMax,
                    input.StorageNumber,
                    input.IncommingDateMin,
                    input.IncommingDateMax,
                    input.FieldId,
                    input.UnitId,
                    input.WorkflowId,
                    input.StatusId,
                    input.TypeId,
                    input.UrgencyLevelId,
                    input.SecrecyLevelId,
                    input.SourceType,
                    currentUserId.Value,
                    assignedDocumentIds,
                    input.Sorting,
                    input.MaxResultCount,
                    input.SkipCount);

                return new PagedResultDto<DocumentWithNavigationPropertiesDto>
                {
                    TotalCount = totalCount,
                    Items = ObjectMapper.Map<List<DocumentWithNavigationProperties>, List<DocumentWithNavigationPropertiesDto>>(items)
                };
            }
        }

        return await base.GetListAsync(input);
    }

    public override async Task<IRemoteStreamContent> GetListAsExcelFileAsync(DocumentExcelDownloadDto input)
    {
        if (input.SourceType == DocumentSourceType.Personal)
        {
            var currentUserId = CurrentUser.Id;
            if (currentUserId.HasValue)
            {
                var downloadToken = await _downloadTokenCache.GetAsync(input.DownloadToken);
                if (downloadToken == null || input.DownloadToken != downloadToken.Token)
                {
                    throw new AbpAuthorizationException("Invalid download token: " + input.DownloadToken);
                }

                var assignedDocumentIds = await GetAssignedDocumentIdsAsync(currentUserId.Value);
                var documents = await _documentRepository.GetListWithNavigationPropertiesAsync(
                    input.FilterText,
                    input.No,
                    input.Title,
                    input.CurrentStatus,
                    input.CompletedTimeMin,
                    input.CompletedTimeMax,
                    input.StorageNumber,
                    input.IncommingDateMin,
                    input.IncommingDateMax,
                    input.FieldId,
                    input.UnitId,
                    input.WorkflowId,
                    input.StatusId,
                    input.TypeId,
                    input.UrgencyLevelId,
                    input.SecrecyLevelId,
                    input.SourceType,
                    currentUserId.Value,
                    assignedDocumentIds);

                var items = documents.Select(item => new
                {
                    No = item.Document.No,
                    Title = item.Document.Title,
                    CurrentStatus = item.Document.CurrentStatus,
                    CompletedTime = item.Document.CompletedTime,
                    StorageNumber = item.Document.StorageNumber,
                    IncommingDate = item.Document.IncommingDate,
                    Field = item.Field?.Name,
                    Unit = item.Unit?.Name,
                    Workflow = item.Workflow?.Name,
                    Status = item.Status?.Name,
                    Type = item.Type?.Name,
                    UrgencyLevel = item.UrgencyLevel?.Name,
                    SecrecyLevel = item.SecrecyLevel?.Name,
                    Creator = item.Document.CreatorId
                });

                var memoryStream = new MemoryStream();
                await memoryStream.SaveAsAsync(items);
                memoryStream.Seek(0, SeekOrigin.Begin);
                return new RemoteStreamContent(memoryStream, "Documents.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            }
        }

        return await base.GetListAsExcelFileAsync(input);
    }

    private async Task<List<Guid>> GetAssignedDocumentIdsAsync(Guid userId)
    {
        var assignments = await _documentAssignmentRepository.GetListAsync(receiverUserId: userId);
        return assignments.Select(assignment => assignment.DocumentId).Distinct().ToList();
    }

    public async Task<bool> SendDocumentAsync(SendDocumentInput input)
    {
        try
        {
            _logger.LogInformation("SendDocumentAsync started: DocumentId={DocumentId}, Recipients={RecipientCount}, Departments={DepartmentCount}",
                input.DocumentId,
                input.Recipients?.Count ?? 0,
                input.Departments?.Count ?? 0);

            // Validate input
            if (input.DocumentId == Guid.Empty)
            {
                throw new UserFriendlyException(L["DocumentId is required"]);
            }

            if ((input.Recipients == null || input.Recipients.Count == 0) &&
                (input.Departments == null || input.Departments.Count == 0))
            {
                throw new UserFriendlyException(L["At least one recipient or department is required"]);
            }

            // Get current user
            var currentUserId = CurrentUser.Id;
            if (currentUserId == null)
            {
                throw new UserFriendlyException(L["User not authenticated"]);
            }

            // Get document info
            var document = await _documentRepository.GetAsync(input.DocumentId);

            var allReceiverUserIds = new List<Guid>();

            // Handle individual recipients
            if (input.Recipients != null && input.Recipients.Count > 0)
            {
                allReceiverUserIds.AddRange(input.Recipients);
            }

            // Handle department recipients
            if (input.Departments != null && input.Departments.Count > 0)
            {
                foreach (var departmentId in input.Departments)
                {
                    // Get all users in the department
                    var userDepartments = await _userDepartmentRepository.GetListAsync(ud => ud.DepartmentId == departmentId && ud.IsActive);
                    var departmentUserIds = userDepartments.Select(ud => ud.UserId).ToList();
                    allReceiverUserIds.AddRange(departmentUserIds);
                }
            }

            // Remove duplicates
            allReceiverUserIds = allReceiverUserIds.Distinct().ToList();

            if (allReceiverUserIds.Count == 0)
            {
                throw new UserFriendlyException(L["No valid recipients found"]);
            }

            _logger.LogInformation("Sending document to {RecipientCount} recipients", allReceiverUserIds.Count);

            // Create notification
            var notificationTitleKey = "DocumentReceived";
            var notificationContentKey = $"DocumentReceivedMessage|{document.StorageNumber}|{document.Title}|{CurrentUser.UserName ?? L["System"]}";

            var notification = new Notification(
                GuidGenerator.Create(),
                notificationTitleKey,
                notificationContentKey,
                SourceType.DOCUMENT.ToString(),
                EventType.DOCUMENT_SENT.ToString(),
                RelatedType.DOCUMENT.ToString(),
                "NORMAL",
                document.Id.ToString()
            );

            notification.TenantId = CurrentTenant.Id;
            await _notificationRepository.InsertAsync(notification);

            var now = Clock.Now; // ISSUE-18 FIX: Use ABP Clock instead of DateTime.Now

            // Create notification receivers and document histories for each user
            foreach (var receiverUserId in allReceiverUserIds)
            {
                // Create notification receiver
                var notificationReceiver = new NotificationReceiver(
                    GuidGenerator.Create(),
                    notification.Id,
                    receiverUserId,
                    false
                );
                notificationReceiver.TenantId = CurrentTenant.Id;
                await _notificationReceiverRepository.InsertAsync(notificationReceiver);

                // Create document history with Action = TRINH
                var documentHistory = await _documentHistoryManager.CreateAsync(
                    input.DocumentId,
                    currentUserId,
                    receiverUserId,
                    "TRINH",
                    $"Document sent from user {CurrentUser.UserName ?? L["System"]}"
                );

                // Check if DocumentAssignment already exists for this document and user
                var existingAssignments = await _documentAssignmentRepository.GetListAsync(
                    documentId: input.DocumentId,
                    receiverUserId: receiverUserId
                );

                var existingAssignment = existingAssignments.FirstOrDefault();

                if (existingAssignment != null)
                {
                    // DocumentAssignment exists → Update status to DONE and ProcessedAt
                    existingAssignment.Status = DocumentAssignmentStatus.DONE.ToString();
                    existingAssignment.ProcessedAt = now;
                    existingAssignment.IsCurrent = true;
                    await _documentAssignmentRepository.UpdateAsync(existingAssignment);
                    
                    _logger.LogInformation("Updated existing DocumentAssignment: DocumentId={DocumentId}, ReceiverUserId={ReceiverUserId}",
                        input.DocumentId, receiverUserId);
                }
                else
                {
                    // DocumentAssignment doesn't exist → Create new with status DONE
                    var documentAssignment = await _documentAssignmentManager.CreateAsync(
                        input.DocumentId,
                        null,
                        receiverUserId,
                        (int)DocumentAssignmentStepOrder.ORIGINAL, // ORIGINAL
                        DocumentAssignmentActionType.VIEW.ToString(), // VIEW
                        DocumentAssignmentStatus.DONE.ToString(),
                        now, // AssignedAt
                        now, // ProcessedAt
                        true // IsCurrent
                    );
                    
                    _logger.LogInformation("Created new DocumentAssignment: DocumentId={DocumentId}, ReceiverUserId={ReceiverUserId}",
                        input.DocumentId, receiverUserId);
                }
            }

            // Publish event to RabbitMQ for real-time notification
            await _distributedEventBus.PublishAsync(
                new NotificationCreatedEto
                {
                    NotificationId = notification.Id,
                    ReceiverUserIds = allReceiverUserIds
                }
            );

            _logger.LogInformation("SendDocumentAsync completed successfully: DocumentId={DocumentId}, SentTo={RecipientCount} users",
                input.DocumentId, allReceiverUserIds.Count);

            // Update document status to DA_GUI (Đã gửi) after successfully sending
            await UpdateDocumentStatusAsync(input.DocumentId, DocumentStatusCode.DA_GUI);

            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in SendDocumentAsync: DocumentId={DocumentId}", input.DocumentId);
            throw;
        }
    }

    public async Task<bool> RevokeDocumentAsync(RevokeDocumentInput input)
    {
        try
        {
            _logger.LogInformation("RevokeDocumentAsync started: DocumentId={DocumentId}", input.DocumentId);

            // Validate input
            if (input.DocumentId == Guid.Empty)
            {
                throw new UserFriendlyException(L["DocumentId is required"]);
            }

            // Get current user
            var currentUserId = CurrentUser.Id;
            if (currentUserId == null)
            {
                throw new UserFriendlyException(L["User not authenticated"]);
            }

            // Get document info
            var document = await _documentRepository.GetAsync(input.DocumentId);

            // Get all document assignments for this document
            var documentAssignments = await _documentAssignmentRepository.GetListAsync(
                documentId: input.DocumentId
            );

            if (documentAssignments == null || documentAssignments.Count == 0)
            {
                _logger.LogWarning("No document assignments found for DocumentId={DocumentId}", input.DocumentId);
                return true;
            }

            // Get all unique receiver user IDs
            var receiverUserIds = documentAssignments
                .Select(da => da.ReceiverUserId)
                .Distinct()
                .ToList();

            _logger.LogInformation("Revoking document from {RecipientCount} recipients", receiverUserIds.Count);

            // Update all document assignments status to REVOKE
            foreach (var documentAssignment in documentAssignments)
            {
                documentAssignment.Status = DocumentAssignmentStatus.REVOKE.ToString();
                await _documentAssignmentRepository.UpdateAsync(documentAssignment);
            }

            // Create notification
            var notificationTitleKey = "DocumentRevoked";
            var notificationContentKey = $"DocumentRevokedMessage|{document.StorageNumber}|{document.Title}|{CurrentUser.UserName ?? L["System"]}";

            var notification = new Notification(
                GuidGenerator.Create(),
                notificationTitleKey,
                notificationContentKey,
                SourceType.DOCUMENT.ToString(),
                EventType.DOCUMENT_REVOKED.ToString(),
                RelatedType.DOCUMENT.ToString(),
                "NORMAL",
                document.Id.ToString()
            );

            notification.TenantId = CurrentTenant.Id;
            await _notificationRepository.InsertAsync(notification);

            // Create notification receivers for each user
            foreach (var receiverUserId in receiverUserIds)
            {
                var notificationReceiver = new NotificationReceiver(
                    GuidGenerator.Create(),
                    notification.Id,
                    receiverUserId,
                    false
                );
                notificationReceiver.TenantId = CurrentTenant.Id;
                await _notificationReceiverRepository.InsertAsync(notificationReceiver);

                // Create document history with Action = THU HOI
                await _documentHistoryManager.CreateAsync(
                    input.DocumentId,
                    currentUserId.Value,
                    receiverUserId,
                    "THU_HOI",
                    $"Revoked document {document.Title} by {CurrentUser.UserName ?? L["System"]}"
                );
            }

            // Publish event to RabbitMQ for real-time notification
            await _distributedEventBus.PublishAsync(
                new NotificationCreatedEto
                {
                    NotificationId = notification.Id,
                    ReceiverUserIds = receiverUserIds
                }
            );

            _logger.LogInformation("RevokeDocumentAsync completed successfully: DocumentId={DocumentId}, RevokedFrom={RecipientCount} users",
                input.DocumentId, receiverUserIds.Count.ToString());

            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error in RevokeDocumentAsync: DocumentId={DocumentId}", input.DocumentId);
            throw;
        }
    }

    /// <summary>
    /// Update document status by DocumentStatusCode enum.
    /// Looks up MasterData by Code and Type = "TRANG_THAI_VB".
    /// </summary>
    private async Task UpdateDocumentStatusAsync(Guid documentId, DocumentStatusCode statusCode)
    {
        try
        {
            var document = await _documentRepository.GetAsync(documentId);
            var code = statusCode.GetCode();

            var statusList = await _masterDataRepository.GetListAsync(
                x => x.Code == code && x.Type == MasterDataType.Status.GetTypeValue());

            var status = statusList.FirstOrDefault();
            if (status == null)
            {
                _logger.LogWarning("MasterData with Code='{Code}' and Type='TRANG_THAI_VB' not found. Document status will not be updated.", code);
                return;
            }

            document.StatusId = status.Id;
            await _documentRepository.UpdateAsync(document);

            _logger.LogInformation("Document status updated to {Code}: DocumentId={DocumentId}, StatusId={StatusId}",
                code, documentId, status.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error updating document status to {Code}: DocumentId={DocumentId}",
                statusCode.GetCode(), documentId);
            // Don't throw - we don't want to fail the parent operation if status update fails
        }
    }
}
