using System;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Caching;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace HC.Documents;

public class DocumentsAppService : DocumentsAppServiceBase, IDocumentsAppService
{
    //<suite-custom-code-autogenerated>
    public DocumentsAppService(IDocumentRepository documentRepository, DocumentManager documentManager, IDistributedCache<DocumentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.MasterDatas.MasterData, Guid> masterDataRepository, IRepository<HC.Units.Unit, Guid> unitRepository, IRepository<HC.Workflows.Workflow, Guid> workflowRepository, ILogger<DocumentsAppServiceBase> logger) : base(documentRepository, documentManager, downloadTokenCache, masterDataRepository, unitRepository, workflowRepository, logger)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...

    public async Task<bool> SendDocumentAsync(SendDocumentInput input)
    {
        return await Task.FromResult(true);
    }
}