using HC.Shared;
using HC.Projects;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectTasks;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using HC.ProjectTaskAssignments;
using HC.ProjectTaskDocuments;
using HC.CalendarEvents;

namespace HC.ProjectTasks;

public partial class ProjectTasksAppService : ProjectTasksAppServiceBase, IProjectTasksAppService
{
    private readonly IProjectTaskAssignmentRepository _projectTaskAssignmentRepository;
    private readonly IProjectTaskDocumentRepository _projectTaskDocumentRepository;
    protected ICalendarEventRepository _calendarEventRepository;

    //<suite-custom-code-autogenerated>
    public ProjectTasksAppService(
        IProjectTaskRepository projectTaskRepository,
        ProjectTaskManager projectTaskManager,
        IDistributedCache<ProjectTaskDownloadTokenCacheItem, string> downloadTokenCache,
        IRepository<HC.Projects.Project, Guid> projectRepository,
        IProjectTaskAssignmentRepository projectTaskAssignmentRepository,
        IProjectTaskDocumentRepository projectTaskDocumentRepository,
        ICalendarEventRepository calendarEventRepository)
        : base(projectTaskRepository, projectTaskManager, downloadTokenCache, projectRepository)
    {
        _projectTaskAssignmentRepository = projectTaskAssignmentRepository;
        _projectTaskDocumentRepository = projectTaskDocumentRepository;
        _calendarEventRepository = calendarEventRepository;
    }
    //</suite-custom-code-autogenerated>

    // Override CreateAsync to add CalendarEvent for ProjectTask
    public override async Task<ProjectTaskDto> CreateAsync(ProjectTaskCreateDto input)
    {
        // Call base method to create task
        var result = await base.CreateAsync(input);

        // Create CalendarEvent for the task
        var calendarEvent = new CalendarEvent(
            GuidGenerator.Create(),
            result.Title,
            result.StartDate,
            result.DueDate, // Default end time
            false, // AllDay
            EventType.TASK_ASSIGNED.ToString(),
            RelatedType.TASK.ToString(),
            EventVisibility.PUBLIC.ToString(),
            $"Task: {result.Title}",
            null,
            result.Id.ToString() // Store Task Id in RelatedId
        );

        calendarEvent.TenantId = CurrentTenant.Id;
        await _calendarEventRepository.InsertAsync(calendarEvent);

        return result;
    }
}