using HC.Shared;
using Volo.Abp.Identity;
using HC.Projects;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectMembers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Notifications;
using HC.NotificationReceivers;
using Volo.Abp.EventBus.Distributed;
using static HC.Notifications.SourceType;
using static HC.Notifications.EventType;
using static HC.Notifications.RelatedType;
using HC.CalendarEvents;
using HC.CalendarEventParticipants;

namespace HC.ProjectMembers;

public partial class ProjectMembersAppService : ProjectMembersAppServiceBase, IProjectMembersAppService
{
    //<suite-custom-code-autogenerated>
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    protected IRepository<HC.Projects.Project, Guid> _projectRepository;
    protected IRepository<Volo.Abp.Identity.IdentityUser, Guid> _identityUserRepository;
    protected IProjectMemberRepository _projectMemberRepository;
    protected ICalendarEventRepository _calendarEventRepository;
    protected ICalendarEventParticipantRepository _calendarEventParticipantRepository;

    public ProjectMembersAppService(
        IProjectMemberRepository projectMemberRepository,
        ProjectMemberManager projectMemberManager,
        IDistributedCache<ProjectMemberDownloadTokenCacheItem, string> downloadTokenCache,
        IRepository<HC.Projects.Project, Guid> projectRepository,
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository,
        INotificationRepository notificationRepository,
        INotificationReceiverRepository notificationReceiverRepository,
        IDistributedEventBus distributedEventBus,
        ICalendarEventRepository calendarEventRepository,
        ICalendarEventParticipantRepository calendarEventParticipantRepository)
        : base(projectMemberRepository, projectMemberManager, downloadTokenCache, projectRepository, identityUserRepository)
    {
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        _projectRepository = projectRepository;
        _identityUserRepository = identityUserRepository;
        _projectMemberRepository = projectMemberRepository;
        _calendarEventRepository = calendarEventRepository;
        _calendarEventParticipantRepository = calendarEventParticipantRepository;
    }
    //</suite-custom-code-autogenerated>
    
    // Override CreateAsync to add notification logic
    public override async Task<ProjectMemberDto> CreateAsync(ProjectMemberCreateDto input)
    {
        // Call base method to create member
        var result = await base.CreateAsync(input);

        // Get project information
        var project = await _projectRepository.GetAsync(input.ProjectId);
        var memberUser = await _identityUserRepository.GetAsync(input.UserId);

        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        string userFullName = CurrentUser.SurName + " " + CurrentUser.Name; 
        var notificationTitleKey = "ProjectMemberAdded";
        var notificationContentKey = $"ProjectMemberAddedMessage|{project.Code}|{project.Name}|{userFullName ?? L["System"]}";

        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.PROJECT.ToString(),
            HC.CalendarEvents.EventType.PROJECT_MEMBER_ADDED.ToString(),
            HC.CalendarEvents.RelatedType.PROJECT.ToString(),
            "NORMAL",
            project.Id.ToString()
        );

        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);

        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.UserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);

        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.UserId }
            }
        );

        await AddCalendarParticipantForProjectAsync(project.Id, input.UserId);

        return result;
    }
    
    // Override DeleteAsync to add notification logic
    public override async Task DeleteAsync(Guid id)
    {
        // Get member info before deleting
        var memberWithNav = await _projectMemberRepository.GetWithNavigationPropertiesAsync(id);
        var project = memberWithNav.Project;
        var user = memberWithNav.User;
        string userFullName = CurrentUser.SurName + " " + CurrentUser.Name; 

        await RemoveCalendarParticipantForProjectAsync(project.Id, user.Id);

        // Call base method to delete member
        await base.DeleteAsync(id);

        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "ProjectMemberRemoved";
        var notificationContentKey = $"ProjectMemberRemovedMessage|{project.Code}|{project.Name}|{userFullName ?? L["System"]}";

        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.PROJECT.ToString(),
            HC.CalendarEvents.EventType.PROJECT_MEMBER_REMOVED.ToString(),
            HC.CalendarEvents.RelatedType.PROJECT.ToString(),
            "NORMAL",
            project.Id.ToString()
        );

        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);

        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            user.Id,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);

        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { user.Id }
            }
        );
    }
    
    // Override UpdateAsync to add notification logic
    public override async Task<ProjectMemberDto> UpdateAsync(Guid id, ProjectMemberUpdateDto input)
    {
        // Call base method to update member
        var result = await base.UpdateAsync(id, input);
        
        // Get project and user information
        var project = await _projectRepository.GetAsync(input.ProjectId);
        var memberUser = await _identityUserRepository.GetAsync(input.UserId);
        
        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        string userFullName = CurrentUser.SurName + " " + CurrentUser.Name; 
        var notificationTitleKey = "ProjectMemberUpdated";
        var notificationContentKey = $"ProjectMemberUpdatedMessage|{project.Code}|{project.Name}|{userFullName ?? L["System"]}";
        
        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.PROJECT.ToString(),
            HC.CalendarEvents.EventType.PROJECT_MEMBER_UPDATED.ToString(),
            HC.CalendarEvents.RelatedType.PROJECT.ToString(),
            "NORMAL",
            project.Id.ToString()
        );
        
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);
        
        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.UserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);
        
        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.UserId }
            }
        );
        
        return result;
    }

    public override async Task DeleteByIdsAsync(List<Guid> projectmemberIds)
    {
        foreach (var memberId in projectmemberIds)
        {
            var memberWithNav = await _projectMemberRepository.GetWithNavigationPropertiesAsync(memberId);
            await RemoveCalendarParticipantForProjectAsync(memberWithNav.Project.Id, memberWithNav.User.Id);
        }

        await base.DeleteByIdsAsync(projectmemberIds);
    }

    public override async Task DeleteAllAsync(GetProjectMembersInput input)
    {
        var members = await _projectMemberRepository.GetListWithNavigationPropertiesAsync(
            input.FilterText, input.MemberRole, input.JoinedAtMin, input.JoinedAtMax, input.ProjectId, input.UserId);

        foreach (var member in members)
        {
            await RemoveCalendarParticipantForProjectAsync(member.Project.Id, member.User.Id);
        }

        await base.DeleteAllAsync(input);
    }

    private async Task AddCalendarParticipantForProjectAsync(Guid projectId, Guid userId)
    {
        var calendarEvent = await FindProjectCalendarEventAsync(projectId);
        if (calendarEvent == null)
        {
            return;
        }

        var alreadyParticipant = await _calendarEventParticipantRepository.AnyAsync(
            p => p.CalendarEventId == calendarEvent.Id && p.IdentityUserId == userId);

        if (alreadyParticipant)
        {
            return;
        }

        var participant = new CalendarEventParticipant(
            GuidGenerator.Create(),
            calendarEvent.Id,
            userId,
            ParticipantResponse.INVITED.ToString(),
            false);
        participant.TenantId = CurrentTenant.Id;
        await _calendarEventParticipantRepository.InsertAsync(participant);
    }

    private async Task RemoveCalendarParticipantForProjectAsync(Guid projectId, Guid userId)
    {
        var calendarEvent = await FindProjectCalendarEventAsync(projectId);
        if (calendarEvent == null)
        {
            return;
        }

        var participantQueryable = await _calendarEventParticipantRepository.GetQueryableAsync();
        var participants = await AsyncExecuter.ToListAsync(
            participantQueryable
                .Where(p => p.CalendarEventId == calendarEvent.Id)
                .Where(p => p.IdentityUserId == userId));

        foreach (var participant in participants)
        {
            await _calendarEventParticipantRepository.DeleteAsync(participant.Id);
        }
    }

    private async Task<CalendarEvent?> FindProjectCalendarEventAsync(Guid projectId)
    {
        var queryable = await _calendarEventRepository.GetQueryableAsync();
        var calendarEvents = await AsyncExecuter.ToListAsync(
            queryable
                .Where(e => e.EventType == HC.CalendarEvents.EventType.TASK_ASSIGNED.ToString())
                .Where(e => e.RelatedType == HC.CalendarEvents.RelatedType.PROJECT.ToString())
                .Where(e => e.RelatedId == projectId.ToString()));

        return calendarEvents.FirstOrDefault();
    }
}