using HC.Shared;
using Volo.Abp.Identity;
using HC.Notifications;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.NotificationReceivers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Volo.Abp.Users;
using Volo.Abp.Localization;

namespace HC.NotificationReceivers;

public class NotificationReceiversAppService : NotificationReceiversAppServiceBase, INotificationReceiversAppService
{
    //<suite-custom-code-autogenerated>
    public NotificationReceiversAppService(INotificationReceiverRepository notificationReceiverRepository,
     NotificationReceiverManager notificationReceiverManager, 
     IDistributedCache<NotificationReceiverDownloadTokenCacheItem, string> downloadTokenCache, 
     IRepository<HC.Notifications.Notification, Guid> notificationRepository,
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) 
      : base(notificationReceiverRepository, notificationReceiverManager, downloadTokenCache, notificationRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    
    // Mark all unread notifications as read for current user
    public virtual async Task MarkAllAsReadAsync(string? sourceType = null)
    {
        var currentUserId = CurrentUser.Id;
        if (currentUserId == null)
        {
            return;
        }

        // Get all unread notification receivers for current user with navigation properties
        var input = new GetNotificationReceiversInput
        {
            IdentityUserId = currentUserId,
            IsRead = false,
            SourceType = sourceType,
            MaxResultCount = int.MaxValue,
            SkipCount = 0
        };

        var result = await _notificationReceiverRepository.GetListWithNavigationPropertiesAsync(
            input.FilterText,
            input.IsRead,
            input.ReadAtMin,
            input.ReadAtMax,
            input.NotificationId,
            input.IdentityUserId,
            input.Sorting,
            input.MaxResultCount,
            input.SkipCount,
            input.SourceType,
            input.CreationTimeMin,
            input.CreationTimeMax
        );

        var now = DateTime.UtcNow;

        foreach (var item in result)
        {
            item.NotificationReceiver.IsRead = true;
            item.NotificationReceiver.ReadAt = now;
            await _notificationReceiverRepository.UpdateAsync(item.NotificationReceiver);
        }
    }

    // Mark a specific notification as read for current user
    public virtual async Task MarkAsReadAsync(Guid notificationId)
    {
        var currentUserId = CurrentUser.Id;
        if (currentUserId == null)
        {
            return;
        }

        // Find the notification receiver for this notification and current user
        // Don't filter by IsRead to check if it's already read
        var input = new GetNotificationReceiversInput
        {
            NotificationId = notificationId,
            IdentityUserId = currentUserId,
            MaxResultCount = 1,
            SkipCount = 0
        };

        var result = await _notificationReceiverRepository.GetListWithNavigationPropertiesAsync(
            input.FilterText,
            input.IsRead,
            input.ReadAtMin,
            input.ReadAtMax,
            input.NotificationId,
            input.IdentityUserId,
            input.Sorting,
            input.MaxResultCount,
            input.SkipCount,
            input.SourceType,
            input.CreationTimeMin,
            input.CreationTimeMax
        );

        var notificationReceiver = result.FirstOrDefault();
        if (notificationReceiver != null)
        {
            // Check if already marked as read
            if (notificationReceiver.NotificationReceiver.IsRead)
            {
                // Already read, no need to update
                return;
            }

            // Mark as read
            notificationReceiver.NotificationReceiver.IsRead = true;
            notificationReceiver.NotificationReceiver.ReadAt = DateTime.UtcNow;
            await _notificationReceiverRepository.UpdateAsync(notificationReceiver.NotificationReceiver);
        }
    }

    public virtual async Task<PagedResultDto<NotificationReceiverWithLocalizedNotificationDto>> GetMyListWithLocalizedMessagesAsync(
        GetMyNotificationsInput input)
    {
        var userId = CurrentUser.Id;
        if (userId == null)
        {
            return new PagedResultDto<NotificationReceiverWithLocalizedNotificationDto> { TotalCount = 0, Items = new List<NotificationReceiverWithLocalizedNotificationDto>() };
        }

        async Task<PagedResultDto<NotificationReceiverWithLocalizedNotificationDto>> QueryAndMapAsync()
        {
            var listInput = new GetNotificationReceiversInput
            {
                FilterText = input.FilterText,
                IsRead = input.IsRead,
                SourceType = input.SourceType,
                ReadAtMin = input.ReadAtMin,
                ReadAtMax = input.ReadAtMax,
                NotificationId = input.NotificationId,
                IdentityUserId = userId,
                CreationTimeMin = input.CreationTimeMin,
                CreationTimeMax = input.CreationTimeMax,
                Sorting = input.Sorting,
                MaxResultCount = input.MaxResultCount,
                SkipCount = input.SkipCount
            };

            var totalCount = await _notificationReceiverRepository.GetCountAsync(
                listInput.FilterText,
                listInput.IsRead,
                listInput.ReadAtMin,
                listInput.ReadAtMax,
                listInput.NotificationId,
                listInput.IdentityUserId,
                listInput.SourceType,
                listInput.CreationTimeMin,
                listInput.CreationTimeMax);

            var items = await _notificationReceiverRepository.GetListWithNavigationPropertiesAsync(
                listInput.FilterText,
                listInput.IsRead,
                listInput.ReadAtMin,
                listInput.ReadAtMax,
                listInput.NotificationId,
                listInput.IdentityUserId,
                listInput.Sorting,
                listInput.MaxResultCount,
                listInput.SkipCount,
                listInput.SourceType,
                listInput.CreationTimeMin,
                listInput.CreationTimeMax);

            var dtos = new List<NotificationReceiverWithLocalizedNotificationDto>(items.Count);
            foreach (var item in items)
            {
                var row = ObjectMapper.Map<NotificationReceiverWithNavigationProperties, NotificationReceiverWithNavigationPropertiesDto>(item);
                row.Notification.Title = LocalizeNotificationTitle(row.Notification.Title);
                row.Notification.Content = LocalizeNotificationContent(row.Notification.Content);
                dtos.Add(new NotificationReceiverWithLocalizedNotificationDto
                {
                    NotificationReceiver = row.NotificationReceiver,
                    Notification = row.Notification,
                    IdentityUser = row.IdentityUser
                });
            }

            return new PagedResultDto<NotificationReceiverWithLocalizedNotificationDto>
            {
                TotalCount = totalCount,
                Items = dtos
            };
        }

        if (!string.IsNullOrWhiteSpace(input.Culture) && CultureHelper.IsValidCultureCode(input.Culture))
        {
            using (CultureHelper.Use(input.Culture!, input.Culture!))
            {
                return await QueryAndMapAsync();
            }
        }

        return await QueryAndMapAsync();
    }

    private string LocalizeNotificationTitle(string? title)
    {
        if (string.IsNullOrEmpty(title))
        {
            return string.Empty;
        }

        try
        {
            return L[title]?.Value ?? title;
        }
        catch
        {
            return title;
        }
    }

    private string LocalizeNotificationContent(string? content)
    {
        if (string.IsNullOrEmpty(content))
        {
            return string.Empty;
        }

        var parts = content.Split('|');
        if (parts.Length > 1)
        {
            var key = parts[0];
            var parameters = parts.Skip(1).ToArray();
            try
            {
                var localizedString = L[key]?.Value;
                if (string.IsNullOrEmpty(localizedString))
                {
                    return content;
                }

                return string.Format(localizedString, parameters);
            }
            catch
            {
                return content;
            }
        }

        try
        {
            return L[content]?.Value ?? content;
        }
        catch
        {
            return content;
        }
    }
}
