using HC.DocumentAssignments;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.DocumentWorkflowInstanceLogss;

public class DocumentWorkflowInstanceLogs : DocumentWorkflowInstanceLogsBase
{
    //<suite-custom-code-autogenerated>
    protected DocumentWorkflowInstanceLogs()
    {
    }

    public DocumentWorkflowInstanceLogs(Guid id, Guid documentWorkflowInstanceId, Guid? documentAssignmentId, Guid? actorUserId, string action, string? actorRole = null, string? fromStatus = null, string? toStatus = null, string? note = null) : base(id, documentWorkflowInstanceId, documentAssignmentId, actorUserId, action, actorRole, fromStatus, toStatus, note)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}