using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.DocumentWorkflowInstanceLogss;

public class DocumentWorkflowInstanceLogsManager : DocumentWorkflowInstanceLogsManagerBase
{
    //<suite-custom-code-autogenerated>
    public DocumentWorkflowInstanceLogsManager(IDocumentWorkflowInstanceLogsRepository documentWorkflowInstanceLogsRepository) : base(documentWorkflowInstanceLogsRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}