using HC.Shared;
using HC.SurveyLocations;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveySessions;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;

namespace HC.SurveySessions;

public class SurveySessionsAppService : SurveySessionsAppServiceBase, ISurveySessionsAppService
{
    //<suite-custom-code-autogenerated>
    protected ISurveySessionRepository _surveySessionRepository;
    protected SurveySessionManager _surveySessionManager;
    protected IRepository<HC.SurveyLocations.SurveyLocation, Guid> _surveyLocationRepository;

    public SurveySessionsAppService(ISurveySessionRepository surveySessionRepository, SurveySessionManager surveySessionManager, IDistributedCache<SurveySessionDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.SurveyLocations.SurveyLocation, Guid> surveyLocationRepository) : base(surveySessionRepository, surveySessionManager, downloadTokenCache, surveyLocationRepository)
    {
        _surveySessionRepository = surveySessionRepository;
        _surveySessionManager = surveySessionManager;
        _surveyLocationRepository = surveyLocationRepository;
    }
    //</suite-custom-code-autogenerated>
    
    /// <summary>
    /// Public API to create survey session without authentication
    /// </summary>
    [AllowAnonymous]
    public virtual async Task<SurveySessionDto> CreatePublicSurveySessionAsync(SurveySessionCreateDto input)
    {
        var surveySession = await _surveySessionManager.CreateAsync(
            input.SurveyLocationId,
            input.SurveyTime,
            input.SessionDisplay ?? $"{input.FullName}_{input.PhoneNumber}_{input.SurveyLocationId}_{input.SurveyTime:ddMMyyyyHHmm}",
            input.FullName,
            input.PhoneNumber,
            input.PatientCode,
            input.DeviceType?.ToString(),
            input.Note
        );

        await _surveySessionRepository.InsertAsync(surveySession);
        return ObjectMapper.Map<SurveySession, SurveySessionDto>(surveySession);
    }
}