<Project Sdk="Microsoft.NET.Sdk">
    
    
  <PropertyGroup><LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Volo.Abp.Elsa</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Volo.Abp.Elsa.Domain.Shared\Volo.Abp.Elsa.Domain.Shared.csproj" />
    <PackageReference Include="../../../../../abp/framework/src/Volo.Abp.Ddd.Domain/Volo.Abp.Ddd.Domain.csproj" VersionOverride="10.0.1" />
    <PackageReference Include="../../../licensing/Volo.Abp.Commercial.SuiteTemplates/Volo.Abp.Commercial.SuiteTemplates.csproj" VersionOverride="10.0.1" />
  </ItemGroup>
</Project>